'use client';
import {useEffect,useState} from 'react';
import {Wrench} from 'lucide-react';
import {z} from 'zod';
import AssemblyViewer from '@/components/assembly-viewer';
import {vehicleCatalog} from '@/lib/vehicle-catalog';
type Part={id:string;name:string;system:string;layer:string};
const manifestSchema=z.object({revision:z.number(),parts:z.array(z.object({id:z.string(),name:z.string(),system:z.string(),layer:z.string()})),limitations:z.array(z.string()),origin:z.string(),sourceRevision:z.string()});
type Manifest=z.infer<typeof manifestSchema>;
export default function ComponentsPage(){
 const [engineId,setEngineId]=useState(vehicleCatalog.engines[0].id),[manifest,setManifest]=useState<Manifest|null>(null),[error,setError]=useState(''),[selected,setSelected]=useState<string|null>(null),[layer,setLayer]=useState('all'),[cutaway,setCutaway]=useState(false),[reset,setReset]=useState(0),[query,setQuery]=useState('');
 useEffect(()=>{const id=new URLSearchParams(location.search).get('engine');if(vehicleCatalog.engines.some(e=>e.id===id))setEngineId(id!);},[]);
 const engine=vehicleCatalog.engines.find(e=>e.id===engineId)!;
 useEffect(()=>{setManifest(null);setError('');setSelected(null);setLayer('all');setCutaway(false);if(!engine.assetUrl)return;const abort=new AbortController();fetch('/models/components/'+engine.id+'-parts.json',{signal:abort.signal}).then(r=>{if(!r.ok)throw Error('Component inventory unavailable');return r.json()}).then(data=>setManifest(manifestSchema.parse(data))).catch(e=>{if(e.name!=='AbortError')setError('Component inventory unavailable. Reload to try again.')});return()=>abort.abort();},[engine.id,engine.assetUrl]);
 const hidden=manifest?.parts.filter(p=>layer!=='all'&&p.layer!==layer).map(p=>p.id)||[];
 const parts=manifest?.parts.filter(p=>!hidden.includes(p.id)&&`${p.name} ${p.id}`.toLowerCase().includes(query.toLowerCase()))||[];
 const part=manifest?.parts.find(p=>p.id===selected);
 return <div className="app-shell"><header className="topbar"><a className="brand" href="/"><span className="brand-mark"><Wrench size={21}/></span>wrenchwise<span className="alpha">ALPHA</span></a><nav><a href="/catalog">Vehicle families</a><a href="/assembly">GS assembly</a></nav></header><main className="catalog-main">
  <div className="eyebrow orange">SHARED COMPONENT LIBRARY</div><h1>Engine models</h1><p className="component-notes">Develop a component once, then validate its installation in each vehicle. Core geometry and vehicle-specific equipment stay separately selectable.</p>
  <div className="component-controls"><label>Engine <select aria-label="Engine component" value={engineId} onChange={e=>{setEngineId(e.target.value);history.replaceState(null,'','?engine='+encodeURIComponent(e.target.value))}}>{vehicleCatalog.engines.map(e=><option key={e.id} value={e.id}>{e.name} · {e.architecture}</option>)}</select></label></div>
  <h2>{engine.name}</h2><p className="catalog-asset-status">{engine.assetUrl?'Provisional component study · 0 verified parts':'Geometry not built'}</p>
  <p className="component-notes">{engine.reuseStatus}. {engine.notes}</p>
  {engine.assetUrl?<><div className="component-controls"><label>Geometry layer <select aria-label="Geometry layer" value={layer} onChange={e=>{setLayer(e.target.value);setSelected(null)}}><option value="all">All modeled parts</option><option value="core">Engine core study</option><option value="installation">GS installation equipment</option></select></label><button className="secondary-btn" aria-pressed={cutaway} onClick={()=>setCutaway(!cutaway)}>{cutaway?'Restore casings':'Hide casings'}</button><button className="secondary-btn" onClick={()=>setReset(reset+1)}>Reset view</button><a className="secondary-btn" href={engine.assetUrl} download>Download GLB</a></div>
  <div className="component-layout"><div className="component-view"><AssemblyViewer key={engine.id} visible={['engine','intake','cooling','exhaust']} selected={selected} onSelect={setSelected} explode={0} cutaway={cutaway} cameraView="all" reset={reset} hiddenParts={hidden} modelUrl={engine.assetUrl} label={`${engine.name} provisional component study`}/></div><aside className="component-notes"><h3>{part?.name||'Inspect a component'}</h3><p>{part?`${part.layer==='core'?'Engine core study':'GS installation equipment'} · unverified geometry`:'Select a mesh or an inventory item. Drag to orbit and scroll to zoom.'}</p><p>{manifest?`${manifest.parts.length} modeled groups · source ${manifest.sourceRevision}`:error||'Loading inventory…'}</p><input className="family-field" aria-label="Search component parts" placeholder="Find a part" value={query} onChange={e=>setQuery(e.target.value)}/><div className="component-parts">{parts.map(p=><button key={p.id} aria-pressed={p.id===selected} onClick={()=>setSelected(p.id)}>{p.name}</button>)}</div></aside></div>
  <details className="catalog-coverage"><summary>Model limits and source evidence</summary><p>{manifest?.origin}</p><ul>{manifest?.limitations.map(l=><li key={l}>{l}</li>)}</ul><a href="/assembly">Open the full S160 evidence and missing-parts inventory</a></details></>:<p className="component-notes">This engine has no component asset yet. Its catalog configurations remain available as vehicle references.</p>}
  <h3>Linked vehicle research</h3><p className="component-notes">These links identify research targets; they do not certify interchangeable parts.</p><div className="component-controls">{engine.recordIds.map(id=>{const r=vehicleCatalog.records.find(r=>r.id===id)!;return <a className="secondary-btn" key={id} href={`/?vehicle=${id}`}>{r.make} {r.name} · {r.generation}</a>})}</div><p className="component-notes"><a href={engine.sourceUrl} target="_blank" rel="noreferrer">Manufacturer reference</a> · {engine.sourceScope}</p>
 </main></div>
}
