'use client';
import {appPath,localWorkshop} from '@/lib/app-path';
import {listModels,listComments,saveComment,importModel,modelUrl} from '@/lib/workshop-client';
import VehicleCatalogBrowser from '@/components/vehicle-catalog-browser';
import modelLibrary from '@/research/model-library.json';
import AssemblyViewer from '@/components/assembly-viewer';
import {serviceStudies} from '@/lib/s160-service';
import { useEffect, useState, useCallback } from 'react';
import { Wrench, Box, CarFront, ChevronDown, BookOpen, Upload, RotateCcw, Layers, MousePointer2, ShieldCheck, ChevronRight, Search, Plus, Check, MessageSquare, Eye, Info, Package, PanelTopOpen, ExternalLink } from 'lucide-react';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Progress } from '@/components/ui/progress';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Checkbox } from '@/components/ui/checkbox';
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from '@/components/ui/select';
import Viewer from '@/components/workshop-viewer';
import { chapters,vehicles,catalogExteriors,exteriorCredits,type ModelRecord,type CommentRecord } from '@/lib/workshop-data';
export default function Home(){
 const [step,setStep]=useState(0),[exploded,setExploded]=useState(false),[reset,setReset]=useState(0),[mode,setMode]=useState('engine'),[hood,setHood]=useState(true),[covers,setCovers]=useState(true),[selected,setSelected]=useState('Engine block');
 const [dialog,setDialog]=useState<'library'|'about'|'upload'|null>(null),[vehicle,setVehicle]=useState('gs300'),[models,setModels]=useState<ModelRecord[]>([]),[modelId,setModelId]=useState('demo'),[libraryError,setLibraryError]=useState(''),[modelsLoading,setModelsLoading]=useState(true);
 const [comments,setComments]=useState<CommentRecord[]>([]),[commentsLoading,setCommentsLoading]=useState(false),[commentError,setCommentError]=useState(''),[author,setAuthor]=useState(''),[body,setBody]=useState(''),[savingComment,setSavingComment]=useState(false),[activeTab,setActiveTab]=useState('guide');
 const [uploading,setUploading]=useState(false),[uploadError,setUploadError]=useState(''),[rights,setRights]=useState(false),[uploadVehicle,setUploadVehicle]=useState('gs300');
 useEffect(()=>{setSelected(modelId==='demo'&&vehicle==='gs300'?'Engine block':'Select a mesh')},[modelId,vehicle]);
 useEffect(()=>{const initial=new URLSearchParams(window.location.search).get('vehicle');if(initial&&vehicles.some(v=>v.id===initial)){setVehicle(initial);setUploadVehicle(initial);setMode('vehicle')}},[]);
 const current=vehicles.find(v=>v.id===vehicle)!;const asset=models.find(m=>m.id===modelId);const demo=vehicle==='gs300'&&!asset;const exterior=!demo&&!asset?catalogExteriors[vehicle]:undefined;const empty=!asset&&!demo&&!exterior;const chapter=chapters[step];const mechanicalStudy=serviceStudies.find(s=>s.id===['engine-layout','timing-covers','timing-drive','pump-drive','timing-drive','engine-layout'][step])!;
 const [assetUrl,setAssetUrl]=useState<string>();
 useEffect(()=>{let active=true;let objectUrl:string|undefined;setAssetUrl(undefined);if(asset)modelUrl(asset.id).then(url=>{objectUrl=url;if(active)setAssetUrl(url);else if(url.startsWith('blob:'))URL.revokeObjectURL(url)}).catch(e=>{if(active)setLibraryError(e.message)});return()=>{active=false;if(objectUrl?.startsWith('blob:'))URL.revokeObjectURL(objectUrl)}},[asset?.id]);
 const loadModels=useCallback(async()=>{setModelsLoading(true);try{const data=await listModels();setModels(data);setLibraryError('');}catch(e){setLibraryError((e as Error).message);}finally{setModelsLoading(false);}},[]);
 useEffect(()=>{void loadModels()},[loadModels]);
 useEffect(()=>{const control=new AbortController();setCommentsLoading(true);setCommentError('');setComments([]);listComments(vehicle,control.signal).then(data=>{if(!control.signal.aborted)setComments(data)}).catch(e=>{if(!control.signal.aborted&&e.name!=='AbortError')setCommentError(e.message)}).finally(()=>{if(!control.signal.aborted)setCommentsLoading(false)});return()=>control.abort()},[vehicle]);
 const chooseStep=useCallback((n:number)=>{setStep(n);setSelected(chapters[n].part);setCovers(n===0||n===1||n===5);if(n===5){setExploded(false);setCovers(true)}},[]);
 const chooseVehicle=useCallback((id:string)=>{setVehicle(id);setUploadVehicle(id);setModelId(models.find(m=>m.vehicle===id)?.id||'demo');setStep(0);setSelected(id==='gs300'?'Engine block':'Select a mesh');setExploded(false);setCovers(false);setMode(id==='gs300'?'engine':'vehicle');setDialog(null)},[models]);
 useEffect(()=>{const ctx=(document as any).modelContext;if(!ctx?.registerTool)return;const lifecycle=new AbortController();const register=(tool:any)=>{try{Promise.resolve(ctx.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}};register({name:'get_workshop_state',description:'Read the current vehicle, model and exploration chapter.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({vehicle:current.name,model:asset?.name||(exterior?'Exterior reference':empty?'No geometry':'Illustrative demo'),chapter:step+1,exploded,view:mode,verifiedRepairGuide:false})});register({name:'show_exploration_chapter',description:'Navigate the illustrative GS 300 anatomy guide to a chapter from 1 to 6. Does not complete a repair.',inputSchema:{type:'object',properties:{chapter:{type:'integer',minimum:1,maximum:6}},required:['chapter'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:any)=>{if(!demo)throw new Error('The illustrative GS 300 demo must be selected.');if(!Number.isInteger(input.chapter)||input.chapter<1||input.chapter>6)throw new Error('Chapter must be an integer from 1 to 6.');chooseStep(input.chapter-1);await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));return{chapter:input.chapter,title:chapters[input.chapter-1].title};}});return()=>lifecycle.abort()},[current.name,asset,step,exploded,mode,demo,exterior,empty,chooseStep]);
 async function addComment(e:React.FormEvent){e.preventDefault();setSavingComment(true);setCommentError('');try{const data=await saveComment({vehicle,chapter:step,author,body});setComments(c=>[data,...c]);setBody('');}catch(e){setCommentError((e as Error).message)}finally{setSavingComment(false)}}
 async function upload(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setUploading(true);setUploadError('');const form=new FormData(e.currentTarget);form.set('vehicle',uploadVehicle);form.set('rights',rights?'yes':'no');try{const data=await importModel(form);setModels(m=>[data,...m]);setVehicle(data.vehicle);setModelId(data.id);setMode('engine');setExploded(false);setRights(false);setDialog(null);}catch(e){setUploadError((e as Error).message)}finally{setUploading(false)}}
 const openUpload=()=>{setUploadVehicle(vehicle);setUploadError('');setDialog('upload')};
 return <div className="app-shell"><header className="topbar"><a className="brand" href={appPath("/")}><span className="brand-mark"><Wrench size={21}/></span>wrenchwise<span className="alpha">ALPHA</span></a><nav aria-label="Main navigation"><button className="nav-active" onClick={()=>setDialog(null)}><Box size={17}/>Workshop</button><a className="assembly-nav-link" href={appPath("/catalog")}>Toyota & Lexus</a><a className="assembly-nav-link" href={appPath("/assembly")}><CarFront size={17}/>Full vehicle</a><a className="assembly-nav-link" href={appPath('/library')}><CarFront size={17}/>3D library</a><button onClick={()=>setDialog('about')}><BookOpen size={17}/>About the project</button></nav><button className="contribute-top" onClick={openUpload}><Plus size={16}/>{localWorkshop?'Import a model':'Contribute a model'}</button></header>
 <main><div className="breadcrumb">My workshop <ChevronRight size={14}/> {current.make} {current.name} <ChevronRight size={14}/><span>{demo?'Engine & cooling':'Vehicle reference'}</span></div><div className="page-heading"><div><div className="eyebrow">THE INTERACTIVE WORKSHOP</div><h1>Know your car. <span>Inside out.</span></h1></div><button className="vehicle-picker" onClick={()=>setDialog('library')}><span className="vehicle-icon"><CarFront/></span><span><small>YOUR VEHICLE</small><strong>{vehicle==='gs300'?'2000 ':''}{current.make} {current.name}</strong><small>{asset?asset.fitment:current.detail}</small></span><ChevronDown size={18}/></button></div>
  <section className="model-library-banner" aria-label="New Lexus and Toyota models"><div><strong>{modelLibrary.models.length} more Lexus & Toyota 3D models</strong><p>SC300, LC500, GS350, LS500, LM, RX350, Supra, MR2, Camry, Prius and more. Rotate, zoom and download.</p></div><a className="primary-btn" href={appPath('/library/')}>Explore all {modelLibrary.models.length} models →</a></section>
 <div className="workshop"><section className="viewport" aria-label="3D workshop"><div className="viewer-top"><span className="pill"><span className="tiny-dot"/>3D EXPLORER</span><button className="model-tag" onClick={()=>setDialog('about')}><Info size={13}/>{asset?(localWorkshop?'Unverified import':'Unverified upload'):exterior?'Exterior reference':empty?'3D model needed':'Illustrative model'}</button></div>
 {empty?<div className="model-empty"><CarFront size={54}/><h2>{current.make} {current.name}</h2><p>{current.detail}. This record needs vehicle-specific geometry before 3D exploration is available.</p><p className="catalog-empty-note">{current.notes}</p><a className="resource-link" href={current.sourceUrl} target="_blank" rel="noreferrer">View reference source <ExternalLink size={14}/></a><button className="primary-btn" onClick={openUpload}><Upload size={17}/>{localWorkshop?'Import a model':'Upload a model'}</button><button className="text-button" onClick={()=>chooseVehicle('gs300')}>Explore the GS 300 demo</button></div>:<>{exterior?<AssemblyViewer modelUrl={exterior} label={current.make+' '+current.name+' exterior reference'} visible={['body','interior','wheels']} selected={selected} explode={0} cutaway={false} cameraView='vehicle' reset={reset} onSelect={setSelected}/>:demo?<AssemblyViewer visible={mode==='vehicle'?['body','engine','transmission','driveline','suspension','brakes','wheels','cooling','intake','exhaust','electrical','interior','structure']:['engine','intake','cooling','electrical']} selected={({ 'Engine block':'engine-block','Cylinder head':'cylinder-head','Timing covers':'timing-cover-upper','Timing belt':'timing-belt','Water pump':'water-pump','Camshaft sprockets':'vvti-gear','Crankshaft pulley':'crank-damper','Tensioner':'timing-tensioner'} as Record<string,string>)[selected]||selected} explode={exploded?.45:0} cutaway={false} hiddenParts={mode==='vehicle'?(hood?['hood']:[]):[...mechanicalStudy.hidden.filter(id=>!covers||(!id.startsWith('timing-cover-upper')&&!id.startsWith('timing-cover-lower'))),...(!covers?['timing-cover-upper','timing-cover-lower','engine-cover','engine-cover-lettering',...Array.from({length:4},(_,i)=>'engine-cover-nut-'+(i+1))]:[])]} focusIds={mode==='engine'?mechanicalStudy.focus:undefined} partOffsets={mode==='engine'?mechanicalStudy.offsets:undefined} cameraView={mode==='engine'?mechanicalStudy.camera:mode} reset={reset} onSelect={setSelected}/>:asset&&!assetUrl?<div className="assembly-loading" role="status">{libraryError||'Loading your model…'}</div>:<Viewer step={step} exploded={exploded} reset={reset} asset={assetUrl} mode={mode} hood={hood} covers={covers} selected={selected} onSelect={setSelected}/>}<div className="viewer-title"><span className="eyebrow">{asset?(localWorkshop?'LOCAL MODEL':'COMMUNITY MODEL'):exterior?'EXTERIOR REFERENCE':mode==='vehicle'?'GS 300 / REFERENCE STUDY':'POWERTRAIN / 01'}</span><h2>{asset?asset.name:exterior?current.make+' '+current.name:mode==='vehicle'?'2000 Lexus GS 300.':'Meet the inline-six.'}</h2><p>{asset?asset.fitment:exterior?'CC BY 4.0 · Exact trim and geometry unverified':'Rotate. Explore. Understand every layer.'}</p></div>
 {demo&&<div className="mode-switch"><button aria-pressed={mode==='engine'} className={mode==='engine'?'active':''} onClick={()=>setMode('engine')}><Box size={14}/>Engine</button><button aria-pressed={mode==='vehicle'} className={mode==='vehicle'?'active':''} onClick={()=>setMode('vehicle')}><CarFront size={14}/>Vehicle</button></div>}
 <div className="view-controls"><button title="Reset view" aria-label="Reset view" onClick={()=>setReset(reset+1)}><RotateCcw size={19}/></button>{demo&&<><button title="Exploded view" aria-label="Exploded view" aria-pressed={exploded} className={exploded?'selected':''} onClick={()=>setExploded(!exploded)}><Layers size={19}/></button><button title="Show timing covers" aria-label="Show timing covers" aria-pressed={covers} className={covers?'selected':''} onClick={()=>setCovers(!covers)}><Eye size={19}/></button>{mode==='vehicle'&&<button title="Remove hood" aria-label="Remove hood" aria-pressed={hood} className={hood?'selected':''} onClick={()=>setHood(!hood)}><PanelTopOpen size={19}/></button>}</>}</div>
 <div className="part-label" aria-live="polite"><span className="part-icon"><MousePointer2 size={17}/></span><div><small>{demo?'SELECTED COMPONENT':'SELECTED MESH'}</small><strong>{selected}</strong></div><span className="part-line"/></div></>}
 <div className="viewer-bottom"><span><MousePointer2 size={14}/> Drag to rotate <i/> Scroll to zoom</span><span>{empty?'CATALOG RECORD':asset||exterior?'GLB MODEL':mode==='vehicle'?'S160 ASSEMBLY':'ENGINE VIEW'}</span></div></section>
 <aside className="guide"><div className="guide-heading"><div className="eyebrow orange">{demo?'GUIDED EXPLORATION':'YOUR WORKSHOP'}</div><h2>{demo?<>Timing belt &<br/>water pump</>:<>{current.make} {current.name}<br/>model explorer</>}</h2><p>{demo?'2000 Lexus GS 300 · 2JZ-GE':asset?asset.fitment:'Help build this vehicle’s workshop.'}</p><div className="guide-tags"><span>{demo?'6 chapters':asset?(localWorkshop?'Local model':'Uploaded model'):exterior?'Exterior reference':'Model needed'}</span><span>{demo?'Concept demo':'Not verified'}</span></div></div>
 <Tabs value={activeTab} onValueChange={setActiveTab}><TabsList variant="line" className="guide-tabs"><TabsTrigger value="guide">Guide</TabsTrigger><TabsTrigger value="parts">Parts & tools</TabsTrigger><TabsTrigger value="notes">{localWorkshop?'Local notes':'Comments'}</TabsTrigger></TabsList>
 <TabsContent value="guide">{demo?<><div className="chapter-header"><span>YOUR EXPLORATION</span><span>{step+1} / 6</span></div><Progress value={(step+1)/6*100} className="exploration-progress"/><div className="steps">{chapters.map((c,i)=><button key={c.title} className={'step '+(i===step?'active':'')} onClick={()=>chooseStep(i)} aria-current={i===step?'step':undefined}><span className="step-number">{String(i+1).padStart(2,'0')}</span><span>{c.title}{i===step&&<small>{c.short}</small>}</span>{i===step&&<ChevronRight size={16}/>}</button>)}</div><div className="chapter-detail"><p>{chapter.body}</p><a className="resource-link" href={appPath('/assembly?study='+mechanicalStudy.id)}>Inspect parts and source evidence <ExternalLink size={14}/></a><div className="chapter-tip"><Info size={14}/><span>{chapter.tip}</span></div><div className="chapter-actions"><button className="secondary-btn" disabled={step===0} onClick={()=>chooseStep(step-1)}>Previous</button><button className="primary-btn" onClick={()=>chooseStep(step===5?0:step+1)}>{step===5?'Explore again':'Next chapter'}</button></div></div></>:<div className="tab-copy"><Box size={26} className="orange"/><h3>{asset?'Explore your model':exterior?'Reference geometry acquired':'A workshop in the making'}</h3><p>{asset?'Rotate and inspect your imported model. Click individual meshes to see their names. A guided procedure has not been authored for this asset.':exterior?'This is an exterior and approximate interior reference. Engine, transmission, underbody, fitment and repair steps have not been validated. Source geometry is adapted under CC BY 4.0; attribution is listed below.':'This vehicle needs an accurate model before an interactive guide can be created.'}</p>{exterior&&<dl className="provenance"><dt>Source / creator</dt><dd><a href={exteriorCredits[vehicle]?.source} target="_blank" rel="noreferrer">{exteriorCredits[vehicle]?.author}</a></dd><dt>License</dt><dd>CC BY 4.0</dd><dt>Scope</dt><dd>{current.notes}</dd></dl>}{asset&&<dl className="provenance"><dt>Source / creator</dt><dd>{asset.source}</dd><dt>License</dt><dd>{asset.license}</dd><dt>Validation</dt><dd>{localWorkshop?'Unverified local asset':'Unverified community asset'}</dd></dl>}<button className="secondary-btn" onClick={openUpload}><Upload size={15}/>Add a model</button></div>}</TabsContent>
 <TabsContent value="parts">{!demo?<div className="tab-copy"><Package size={26} className="orange"/><h3>Vehicle-specific parts are not mapped yet.</h3><p>Select the exact generation, engine, transmission and market before choosing parts or authoring a procedure.</p><a className="resource-link" href={current.sourceUrl} target="_blank" rel="noreferrer">View vehicle reference <ExternalLink size={14}/></a></div>:<div className="tab-copy"><Package size={26} className="orange"/><h3>Plan the job before the first bolt.</h3><p>This is a planning checklist, not a vehicle-specific parts list. Confirm fitment and required equipment in the service manual.</p><h4>Parts to verify</h4><ul className="parts-list">{['Timing belt','Water pump and specified seals','Tensioner and idler components','Manufacturer-specified coolant'].map(x=><li key={x}><span/>{x}</li>)}</ul><h4>Equipment to verify</h4><ul className="parts-list">{['Torque wrench and metric sockets','Vehicle-specific holding tools','Fluid collection and protective equipment'].map(x=><li key={x}><span/>{x}</li>)}</ul><p className="muted">Selected fastener counts are now cited in the mechanical studies. Torque application and kit numbers remain unverified.</p><a className="resource-link" href="https://techinfo.toyota.com/" target="_blank" rel="noreferrer">Toyota / Lexus service information <ExternalLink size={14}/></a></div>}</TabsContent>
 <TabsContent value="notes"><div className="comments-panel"><div className="comments-title"><h3>{localWorkshop?'Your local notes':'Workshop discussion'}</h3><span>{comments.length}</span></div><p className="muted">{localWorkshop?'Notes are saved only in this browser. They are not posted publicly or synced to another device.':'Questions and observations about this vehicle. Comments are community input, not verified instructions.'}</p><form onSubmit={addComment}><label htmlFor="author">Your name</label><Input id="author" maxLength={60} value={author} onChange={e=>setAuthor(e.target.value)} required placeholder="How should we call you?"/><label htmlFor="comment">{localWorkshop?'Your note':'Your comment'}</label><Textarea id="comment" maxLength={2000} rows={3} value={body} onChange={e=>setBody(e.target.value)} required placeholder="Write a question or observation…"/><p className="comment-context">Attached to {demo?'chapter '+(step+1):'this model'}</p><button className="primary-btn" disabled={savingComment||!body.trim()||!author.trim()}>{savingComment?'Saving…':(localWorkshop?'Save note':'Post comment')}</button></form>{commentError&&<p role="alert" className="error-message">{commentError}</p>}{commentsLoading?<p role="status">Loading comments…</p>:!comments.length&&!commentError?<div className="comments-empty"><MessageSquare size={25}/><p>{localWorkshop?'Add your first local note.':'Start the conversation.'}</p></div>:comments.map(c=><article className="comment" key={c.id}><div><strong>{c.author}</strong><span>{new Date(c.created_at).toLocaleDateString()}</span></div><small>Chapter {c.chapter+1}</small><p>{c.body}</p></article>)}</div></TabsContent></Tabs>
 <div className="guide-foot"><ShieldCheck size={20}/><p><strong>Learn the layout first.</strong><br/>This is not a verified repair procedure.</p></div></aside></div>
 <div className="workshop-under"><div><ShieldCheck size={18}/><span>Geometry, routing, and placement are illustrative. Consult verified service information before working on a vehicle.</span></div><button onClick={()=>setDialog('about')}>About model accuracy</button></div>
 <footer><span><Wrench size={14}/>An open workshop for curious minds.</span><span>{localWorkshop?'GitHub Pages · Personal imports and notes stay in this browser':'Free to explore · No subscription'}</span></footer></main>
 <Dialog open={dialog!==null} onOpenChange={open=>{if(!open&&!uploading)setDialog(null)}}><DialogContent className={'workshop-dialog '+(dialog==='library'?'library-dialog':'')}><DialogHeader><DialogTitle>{dialog==='library'?'Toyota & Lexus library.':dialog==='upload'?(localWorkshop?'Import into your local workshop.':'Build the next workshop.'):'A workshop worth sharing.'}</DialogTitle><DialogDescription>{dialog==='library'?'Choose a vehicle record. 3D availability and reference coverage are shown separately.':dialog==='upload'?(localWorkshop?'Your file stays in this browser. It is not uploaded or shared. Clearing site storage removes local models and notes.':'Add a model with clear fitment and source information.'):'Wrenchwise is a free, open-source foundation for interactive automotive education.'}</DialogDescription></DialogHeader>
 {dialog==='library'&&<><VehicleCatalogBrowser currentId={vehicle} onChoose={chooseVehicle}/><div className="uploaded-models"><h3>{localWorkshop?'Models saved in this browser':'Uploaded models'}</h3>{modelsLoading?<p>Loading models…</p>:models.length?models.map(m=><button key={m.id} className="model-row" onClick={()=>{chooseVehicle(m.vehicle);setModelId(m.id)}}><Box size={19}/><span><strong>{m.name}</strong><small>{m.fitment} · {(m.size/1024/1024).toFixed(1)} MB</small></span><span>Unverified</span></button>):<p className="muted">{localWorkshop?'No local models yet. Import a GLB to inspect it here.':'No uploaded models yet. Help give this library its next engine.'}</p>}{libraryError&&<div className="error-message" role="alert">{libraryError} <button onClick={loadModels}>Retry</button></div>}<button className="primary-btn" onClick={openUpload}><Upload size={16}/>{localWorkshop?'Import a model':'Contribute a model'}</button>{vehicle==='gs300'&&asset&&<button className="text-button" onClick={()=>{setModelId('demo');setDialog(null)}}>Return to illustrative demo</button>}</div></>}
 {dialog==='upload'&&<form className="upload-form" onSubmit={upload}><label>Vehicle<Select value={uploadVehicle} onValueChange={setUploadVehicle}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{vehicles.map(v=><SelectItem key={v.id} value={v.id}>{v.make} {v.name} · {v.detail}</SelectItem>)}</SelectContent></Select></label><label htmlFor="model-name">Model name<Input id="model-name" name="name" required maxLength={100} placeholder="e.g. 2JZ-GE engine assembly"/></label><label htmlFor="fitment">Year, engine & market<Input id="fitment" name="fitment" required maxLength={180} placeholder="e.g. 2000 GS 300 · 2JZ-GE · US"/></label><label htmlFor="source">Source / creator<Input id="source" name="source" required maxLength={500} placeholder="Creator name or original source URL"/></label><label htmlFor="license">Asset license<Input id="license" name="license" required maxLength={100} placeholder="e.g. CC BY 4.0 or original work"/></label><label htmlFor="model-file" className="upload-file"><Upload size={24}/><strong>Choose your 3D model</strong><span>Self-contained .glb · Up to 20 MB</span><Input type="file" id="model-file" name="file" accept=".glb,model/gltf-binary" required/></label><div className="rights-check"><Checkbox id="rights" checked={rights} onCheckedChange={v=>setRights(v===true)}/><label htmlFor="rights">{localWorkshop?'I created this asset or have permission to use it under the stated license.':'I created this asset or have permission to share it under the stated license.'}</label></div><p className="muted">{localWorkshop?'Imported models are unverified.':'Uploads are unverified.'} Use fewer than one million vertices and embedded textures, preferably 2K or smaller. Imported models support inspection; repair steps need separate authoring and review.</p>{uploadError&&<p role="alert" className="error-message">{uploadError}</p>}<button className="primary-btn full-width" disabled={uploading||!rights}>{uploading?(localWorkshop?'Saving your model…':'Uploading your model…'):(localWorkshop?'Import & explore':'Upload & explore')}</button></form>}
 {dialog==='about'&&<div className="about-content"><div className="about-mark"><Wrench size={27}/></div><h3>Understanding comes before turning a wrench.</h3><p>Explore automotive assemblies in 3D, learn what each component does, and build a library that everyone can contribute to.</p><div className="about-status"><strong>First release: an interactive concept</strong><p>The GS 300 combines a CC BY S160 exterior reference with original, reference-informed mechanical geometry. GS 400, GS 430, RX 300 and Toyota GR Supra visual references are also available. None is factory CAD or a dimensionally validated replica. The GS variants share an adapted body source; their exact trim remains under review.</p><p>The six chapters and eleven mechanical studies teach component relationships. Bolt locations, timing marks, belt routing, torque values, and repair sequences have not been validated. No repair guide is marked verified.</p></div><a className="resource-link" href={appPath("/catalog")}>Browse Toyota and Lexus model records</a><h4>The path to a repair-grade workshop</h4><ol><li>Obtain correctly licensed, vehicle-specific geometry.</li><li>Map named parts and fasteners to exact year, engine, and market.</li><li>Author each repair step against factory service information.</li><li>Have qualified mechanics review and validate it on the vehicle.</li></ol><p>Application code and original procedural geometry are MIT-licensed. Acquired GS/RX/Supra geometry remains CC BY 4.0 with attribution; uploaded assets keep their own licenses. This prototype is independently made and is not affiliated with Lexus or Toyota.</p><a className="resource-link" href="https://techinfo.toyota.com/" target="_blank" rel="noreferrer">Toyota / Lexus service information <ExternalLink size={14}/></a><button className="primary-btn" onClick={openUpload}><Upload size={16}/>{localWorkshop?'Import a model to inspect':'Contribute the first accurate model'}</button></div>}
 </DialogContent></Dialog>
 </div>
}
