'use client';
import {lazy,Suspense,useState} from 'react';
import {ArrowUpRight,Wrench,Layers,BookOpen,ScanEye} from 'lucide-react';
import {appPath} from '@/lib/app-path';
import './garage.css';
import './mechanical-home.css';
const Workshop=lazy(()=>import('./workshop/page'));
const timing=appPath('/assembly/?lesson=timing-belt');
export default function Home(){
 const [legacy]=useState(()=>typeof window!=='undefined'&&/(?:vehicle|asset)=/.test(window.location.search));
 if(legacy)return <Suspense fallback={<main>Opening your workshop…</main>}><Workshop/></Suspense>;
 return <div className="garage-home mechanical-home">
  <div className="garage-topline"><span><i/> INDEPENDENT AUTOMOTIVE EDUCATION</span><span>UNDERSTAND THE PART. UNDERSTAND THE JOB.</span></div>
  <header className="garage-header"><a href={appPath('/')} className="garage-logo" aria-label="Wrenchwise home"><span className="pixel-mark"><Wrench size={25}/></span>wrenchwise<span className="logo-cursor">_</span></a><nav aria-label="Main navigation"><a href="#choose-job">Choose a job</a><a href={appPath('/assembly/?lesson=engine-bay-orientation')}>Learn the layout</a><a href={appPath('/research/#s160-factory-references')}>Factory references</a></nav><a className="garage-header-cta" href={timing}>OPEN WORKSHOP <ArrowUpRight size={17}/></a></header>
  <main>
   <section className="garage-hero">
    <div className="garage-hero-copy"><p className="garage-kicker">A BETTER WAY TO UNDERSTAND WHAT’S UNDER THE HOOD.</p><h1>REAL PARTS.<br/>CLEAR STEPS.<br/><em>YOUR NEXT JOB.</em></h1><p className="garage-lead">Look inside the mechanism before you pick up a wrench. Inspect components in 3D, understand where they belong, and follow the process alongside factory service references.</p><div className="garage-hero-actions"><a className="garage-button" href={timing}>START THE TIMING-BELT WALKTHROUGH <ArrowUpRight size={20}/></a></div><p className="mechanical-home-availability">First walkthrough: 2JZ-GE VVT-i · 2000 Lexus GS300.<br/>Built to grow across engines, systems and vehicles.</p></div>
    <a className="job-hero-card" href={timing} aria-label="Open the 2JZ-GE timing-belt walkthrough"><div className="job-hero-top"><span>WORKSHOP / 001</span><span>2JZ-GE VVT-i</span></div><div className="job-hero-art" aria-hidden="true"><svg viewBox="0 0 460 370"><defs><pattern id="job-grid" width="23" height="23" patternUnits="userSpaceOnUse"><path d="M23 0H0V23" fill="none" stroke="#314832" strokeWidth=".5"/></pattern></defs><rect width="460" height="370" fill="url(#job-grid)"/><g fill="none" stroke="#b9e994" strokeWidth="2"><path d="M105 114a49 49 0 0 1 49-49h151a49 49 0 0 1 47 62L260 297a34 34 0 0 1-60 0l-89-162Z" strokeWidth="9" stroke="#5d7c46"/><circle cx="154" cy="114" r="42"/><circle cx="305" cy="114" r="42"/><circle cx="230" cy="278" r="28"/><circle cx="154" cy="114" r="14"/><circle cx="305" cy="114" r="28"/><circle cx="230" cy="278" r="9"/><circle cx="161" cy="208" r="20"/>{[0,1,2,3,4,5].map(i=><path key={i} transform={'rotate('+i*60+' 154 114)'} d="M154 73v27"/>)}<path d="m143 224-17 17v41h17v-41l17-17M305 71V42h66M154 71V42H70M230 308v29h118" stroke="#739557"/></g><g fill="#c5d2b8" fontSize="10" fontFamily="monospace"><text x="45" y="35">EXHAUST CAM</text><text x="326" y="35">VVT-i CAM</text><text x="270" y="352">CRANKSHAFT</text></g></svg><span>CONCEPT DIAGRAM · NOT A ROUTING REFERENCE</span></div><div className="job-hero-bottom"><div><p>8 PHASES / INTERACTIVE 3D</p><h2>Follow the timing system.</h2><span>Preparation → Access → Inspection → Installation → Checks</span></div><ArrowUpRight size={30}/></div></a>
   </section>
   <section className="job-selection" id="choose-job"><div className="garage-section-head"><div><p className="garage-kicker">START WITH WHAT YOU NEED TO UNDERSTAND</p><h2>CHOOSE YOUR WORKSPACE.</h2></div><span className="job-engine-label">CURRENT ENGINE: 2JZ-GE VVT-i</span></div><div className="job-cards"><a href={timing}><span className="job-number">01 / SERVICE WALKTHROUGH</span><Wrench size={27}/><h3>Timing-belt replacement</h3><p>Understand the factory sequence. See the pulleys, belt and hydraulic tensioner together, then inspect each part.</p><strong>Open walkthrough <ArrowUpRight size={17}/></strong></a><a href={appPath('/assembly/?lesson=engine-bay-orientation')}><span className="job-number">02 / FOUNDATIONS</span><ScanEye size={27}/><h3>Know your engine bay</h3><p>Find the intake, air cleaner and water-pump drive. Learn the names and relationships before approaching a job.</p><strong>Start orientation <ArrowUpRight size={17}/></strong></a><a href={appPath('/assembly/?study=pump-seals')}><span className="job-number">03 / COMPONENT STUDY</span><Layers size={27}/><h3>Water pump & sealing</h3><p>Inspect the pump, gasket, thermostat and bypass connections in a separated anatomy view.</p><strong>Inspect components <ArrowUpRight size={17}/></strong></a></div></section>
   <section className="garage-how" id="how-it-works"><div className="garage-section-head"><div><p className="garage-kicker">FROM THE PAGE TO THE PART</p><h2>SEE HOW THE JOB FITS TOGETHER.</h2></div></div><div className="garage-steps"><article><span>01 <BookOpen size={22}/></span><h3>READ THE PHASE.</h3><p>Follow a clear sequence tied to the right engine and factory chapter.</p></article><article><span>02 <Layers size={22}/></span><h3>INSPECT THE PARTS.</h3><p>Select, rotate and isolate components. See their front, back and underside.</p></article><article><span>03 <Wrench size={22}/></span><h3>CHECK THE REFERENCE.</h3><p>Use the actual service diagrams for alignment, torque and installation details.</p></article></div><p className="garage-learning-note">The current 3D models are educational reconstructions. Exact geometry, clearances and timing marks are not verified. Walkthroughs summarize the process and accompany the full service manual.</p></section>
  </main><footer className="garage-footer"><a className="garage-logo" href={appPath('/')}>wrenchwise_</a><span>MECHANICAL LEARNING, ONE SYSTEM AT A TIME.</span><div><a href={appPath('/research')}>Sources & project notes</a><a href={appPath('/library')}>Vehicle reference archive</a><a href="https://github.com/Zhandolia/wrenchwise" target="_blank" rel="noreferrer">GitHub ↗</a></div><small>Independent project. Not affiliated with vehicle manufacturers.</small></footer>
 </div>;
}
