'use client';
import {lazy, Suspense, useState} from 'react';
import {ArrowUpRight, ArrowRight, Search, Wrench, MoveUpRight, Layers, Zap, Disc3, ChevronRight} from 'lucide-react';
import {appPath} from '@/lib/app-path';
import './garage.css';
const Workshop = lazy(() => import('./workshop/page'));
const systems = [
 {id:'engine',label:'Engine',title:'Everything is connected.',copy:'See how an engine’s layers relate. Separate the illustration to look beneath the surface.',icon:Layers},
 {id:'electrical',label:'Electrical',title:'Follow the connection.',copy:'Start with the battery, then follow the connections. Vehicle-specific routing comes after you select a car.',icon:Zap},
 {id:'brakes',label:'Brakes',title:'Understand the moving parts.',copy:'Get familiar with a disc and caliper. Exact parts and service information depend on your vehicle.',icon:Disc3},
];
function SystemDrawing({system, separated}:{system:string;separated:boolean}) {
 return <svg className="garage-drawing" viewBox="0 0 560 360" role="img" aria-label={'Illustrative '+system+' system diagram'+(separated?', layers separated':'')}>
  <defs><pattern id="tech-grid" width="32" height="18" patternUnits="userSpaceOnUse" patternTransform="skewY(-18)"><path d="M32 0H0V18" fill="none" stroke="#294235" strokeWidth=".65"/></pattern><linearGradient id="block-fill" x2="1" y2="1"><stop stopColor="#243d2b"/><stop offset="1" stopColor="#101c16"/></linearGradient></defs>
  <rect width="560" height="360" fill="url(#tech-grid)"/>
  <g stroke="#b5f969" fill="url(#block-fill)" strokeWidth="1.6" strokeLinejoin="round">
   {system==='engine'&&<>
    <g className="drawing-layer" style={{transform:separated?'translateY(23px)':'none'}}><path d="m130 180 188-66 104 63-187 76Z"/><path d="m130 180 105 73v68l-105-74Z"/><path d="m235 253 187-76v68l-187 76Z"/>{[0,1,2,3].map(i=><g key={i}><ellipse cx={185+i*48} cy={178-i*17} rx="24" ry="13"/><path d={`M${161+i*48} ${178-i*17}v22q24 25 48 0v-22`} strokeDasharray="4 4"/></g>)}<path d="m151 249 64 46m33-20 151-61" strokeWidth="5"/><circle cx="353" cy="250" r="21"/><circle cx="353" cy="250" r="8"/><circle cx="398" cy="228" r="12"/></g>
    <g className="drawing-layer" style={{transform:separated?'translateY(-28px)':'none'}}><path d="m130 140 188-66 104 63-187 76Z"/><path d="m130 140 105 73v27l-105-72Z"/><path d="m235 213 187-76v27l-187 76Z"/>{[0,1,2,3].map(i=><path key={i} d={`m${167+i*43} ${145-i*15} 40 25 18-7-40-25Z`}/>)}<path d="m181 112 101-36 34 19-104 38Z" fill="#b5f969" opacity=".3"/></g>
    {separated&&<g strokeDasharray="4 5" opacity=".6"><path d="M130 140v63M235 211v65M422 137v63"/></g>}
   </>}
   {system==='electrical'&&<><path d="m118 147 137-43 92 62-138 47Z"/><path d="m118 147 91 66v93l-91-68Z"/><path d="m209 213 138-47v92l-138 48Z"/><path d="m144 138 18-6 15 10-18 6Z" fill="#b5f969"/><path d="m269 123 18-6 15 10-18 6Z" fill="#b5f969"/><path d="M160 137V77h190v-24h77v86" fill="none" strokeWidth="5"/><path d="M287 132V94h185v145H347" fill="none" strokeDasharray="8 5"/><circle cx="427" cy="175" r="36"/><circle cx="427" cy="175" r="16"/><path d="M414 142v-14m28 14v-14m-28 80v14m28-14v14"/><path d="m245 229 22-7-9 24 21-8-37 42 10-31-20 7Z" fill="#b5f969"/></>}
   {system==='brakes'&&<><ellipse cx="279" cy="192" rx="94" ry="126" transform="rotate(26 279 192)"/><ellipse cx="279" cy="192" rx="65" ry="92" transform="rotate(26 279 192)"/><ellipse cx="279" cy="192" rx="25" ry="38" transform="rotate(26 279 192)"/>{[0,1,2,3,4,5,6,7,8,9,10,11].map(i=>{const a=i*Math.PI/6;return <circle key={i} cx={279+Math.cos(a)*71} cy={192+Math.sin(a)*102} r="3" fill="#b5f969"/>})}<g className="drawing-layer" style={{transform:separated?'translate(45px,-15px)':'none'}}><path d="m334 84 71 20 16 119-77 22-38-38 11-77Z"/><path d="m334 84 11 99 76 40M345 183l-39 24"/><path d="m357 119 25 7 4 40-24 6Z" fill="#b5f969" opacity=".35"/></g></>}
  </g><g fill="#91a990" fontFamily="monospace" fontSize="10"><text x="22" y="30">ORTHOGRAPHIC / STUDY VIEW</text><text x="22" y="336">ILLUSTRATION · SELECT A CAR FOR AVAILABLE 3D</text><text x="458" y="30">[ {system==='engine'?'01':system==='electrical'?'02':'03'} ]</text></g><path d="M15 52V15h37m456 0h37v37M15 308v37h37m456 0h37v-37" fill="none" stroke="#5d8155"/>
 </svg>;
}
export default function Home() {
 const [legacy] = useState(() => typeof window !== 'undefined' && /(?:vehicle|asset)=/.test(window.location.search));
 const [system,setSystem] = useState(systems[0]);
 const [separated,setSeparated] = useState(false);
 if (legacy) return <Suspense fallback={<main>Opening your workshop…</main>}><Workshop/></Suspense>;
 return <div className="garage-home">
  <div className="garage-topline"><span><i/> INDEPENDENT AUTOMOTIVE LEARNING</span><span>LESS SCROLLING. MORE UNDERSTANDING.</span></div>
  <header className="garage-header"><a href={appPath('/')} className="garage-logo" aria-label="Wrenchwise home"><span className="pixel-mark"><Wrench size={25}/></span>wrenchwise<span className="logo-cursor">_</span></a><nav aria-label="Main navigation"><a href={appPath('/library')}>Find your car</a><a href="#how-it-works">How it works</a><a href={appPath('/components')}>Explore systems</a></nav><a className="garage-header-cta" href={appPath('/library')}>ENTER GARAGE <ArrowUpRight size={17}/></a></header>
  <main>
   <section className="garage-hero">
    <div className="garage-hero-copy"><p className="garage-kicker"><span>FOR THE CURIOUS.</span> AND THE GREASE-COVERED.</p><h1>KNOW YOUR<br/>CAR.<br/><em>INSIDE OUT.</em></h1><p className="garage-lead">Your first car or your forever project. Get under the surface with interactive 3D, explore the parts, and learn how everything works together.</p><div className="garage-hero-actions"><a className="garage-button" href={appPath('/library')}>FIND YOUR CAR <ArrowUpRight size={22}/></a><a className="garage-text-link" href="#how-it-works">New to this? Start here <ChevronRight size={16}/></a></div><div className="garage-footnote"><span className="pixel-cross">✚</span> Built for every kind of car person.</div></div>
    <div className="garage-terminal"><div className="terminal-title"><span><span className="terminal-light"/> SYSTEM_EXPLORER.exe</span><span aria-hidden="true">— □ ×</span></div><div className="terminal-menu" role="group" aria-label="Preview a system">{systems.map(item=><button key={item.id} aria-pressed={system.id===item.id} onClick={()=>{setSystem(item);setSeparated(false);}}><item.icon size={14}/>{item.label}</button>)}</div><SystemDrawing system={system.id} separated={separated}/><div className="terminal-caption"><span>LOOK CLOSER ↗</span>{system.id!=='electrical'&&<button aria-pressed={separated} onClick={()=>setSeparated(!separated)}><Layers size={14}/>{separated?'Bring layers together':'Separate layers'}</button>}</div><div className="terminal-description" aria-live="polite"><h2>{system.title}</h2><p>{system.copy}</p></div><div className="terminal-bottom"><span>VISUAL LEARNING / NO GUESSWORK</span><span>● EXPLORE MODE</span></div></div>
   </section>
   <div className="garage-ticker" aria-label="Project ethos"><span>DAILY DRIVERS</span><span>✳</span><span>WEEKEND PROJECTS</span><span>✳</span><span>FIRST-TIME FIXERS</span><span>✳</span><span>LIFELONG TINKERERS</span><span>✳</span></div>
   <section className="garage-start" id="find-your-car"><div><p className="garage-kicker">01 / YOUR GARAGE STARTS HERE</p><h2>WHAT ARE YOU<br/>WORKING ON?</h2></div><div className="garage-search-area"><form action={appPath('/library/')} method="get"><label htmlFor="garage-search">Find a make, model or body generation</label><div className="garage-search"><Search size={21}/><input id="garage-search" name="q" placeholder="Try Supra, LS400, Camry…"/><button type="submit" aria-label="Search vehicles"><ArrowRight size={24}/></button></div></form><div className="garage-makes"><span>EXPLORE CURRENT COVERAGE</span><a href={appPath('/library/?make=Toyota')}>TOYOTA <ArrowUpRight size={13}/></a><a href={appPath('/library/?make=Lexus')}>LEXUS <ArrowUpRight size={13}/></a><a href={appPath('/catalog')}>ALL VEHICLE RECORDS →</a></div><p className="garage-coverage">An open workshop with a growing roster. Current 3D coverage starts with Toyota and Lexus; available views and lessons are shown for each vehicle.</p></div></section>
   <section className="garage-how" id="how-it-works"><div className="garage-section-head"><div><p className="garage-kicker">02 / FROM “WHAT’S THAT?” TO “GOT IT.”</p><h2>GET TO KNOW THE MACHINE.</h2></div><span className="garage-stamp">OPEN HOOD.<br/>OPEN MIND.</span></div><div className="garage-steps"><article><span>01 <Search size={22}/></span><h3>PICK YOUR RIDE.</h3><p>Find your vehicle and body generation. See what’s available for your specific car.</p></article><article><span>02 <Layers size={22}/></span><h3>LOOK UNDERNEATH.</h3><p>Rotate, zoom and explore. Use system views where mechanical detail is available.</p></article><article><span>03 <Wrench size={22}/></span><h3>MAKE IT CLICK.</h3><p>Follow available anatomy lessons, identify components and check what you’ve learned.</p></article></div><p className="garage-learning-note">Learn the layout before the job. Current studies teach anatomy; verified repair procedures are still in development.</p></section>
   <section className="garage-manifesto"><span className="garage-pixel-flower" aria-hidden="true">✳</span><div><p className="garage-kicker">NO GATEKEEPING. JUST CURIOSITY.</p><h2>YOU DON’T HAVE TO<br/>KNOW IT ALL TO START.</h2><p>Every car person started with a question. This is a place to ask better ones, see the answer from another angle, and build your understanding.</p></div><a className="garage-button garage-button-outline" href={appPath('/library')}>LET’S GET INTO IT <MoveUpRight size={21}/></a></section>
  </main><footer className="garage-footer"><a className="garage-logo" href={appPath('/')}>wrenchwise_</a><span>BUILT FOR CURIOUS MINDS & DIRTY HANDS.</span><div><a href={appPath('/research')}>Sources & project notes</a><a href="https://github.com/Zhandolia/wrenchwise" target="_blank" rel="noreferrer">GitHub ↗</a></div><small>Independent project. Not affiliated with vehicle manufacturers.</small></footer>
 </div>;
}
