'use client';
import {createMaterialHighlighter,isVisibleModelHit,resizePerspective} from '@/lib/viewer-interaction.mjs';
import {addReferenceLighting} from '@/lib/viewer-lighting.mjs';
import {disposeViewerResources} from '@/lib/viewer-resources.mjs';
import { MeshoptDecoder } from 'three/addons/libs/meshopt_decoder.module.js';
import { useEffect, useRef, useState } from 'react';
import * as THREE from 'three';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
type ViewerState={engine:THREE.Group;pieces:THREE.Mesh[];controls:OrbitControls;camera:THREE.PerspectiveCamera;car:THREE.Group;hoodGroup:THREE.Group;cover:THREE.Mesh;invalidate:()=>void;highlight:ReturnType<typeof createMaterialHighlighter>};
export default function Viewer({step,exploded,reset,asset,mode='engine',hood=true,covers=false,selected='',onSelect}:{step:number;exploded:boolean;reset:number;asset?:string;mode?:string;hood?:boolean;covers?:boolean;selected?:string;onSelect?:(part:string)=>void}){
 const [error,setError]=useState(''); const [loading,setLoading]=useState(false);const selectRef=useRef(onSelect); selectRef.current=onSelect;
 const host=useRef<HTMLDivElement>(null); const refs=useRef<ViewerState|null>(null);
 useEffect(()=>{if(!host.current)return;const el=host.current;setLoading(false);setError('');refs.current=null;const scene=new THREE.Scene();const camera=new THREE.PerspectiveCamera(36,Math.max(1,el.clientWidth)/Math.max(1,el.clientHeight),.1,100);camera.position.set(7,5.4,8);let renderer:THREE.WebGLRenderer;try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,powerPreference:'high-performance'});}catch{setError('3D rendering is unavailable on this browser. Try a browser with WebGL enabled. The guide remains available.');return;}renderer.setPixelRatio(Math.min(devicePixelRatio,1.75));renderer.setSize(el.clientWidth,el.clientHeight);renderer.setClearColor(0x000000,0);el.appendChild(renderer.domElement);const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,.8,0);controls.enableDamping=true;controls.minDistance=4;controls.maxDistance=17;controls.maxPolarAngle=Math.PI*.8;
 const environment=asset?addReferenceLighting(scene,renderer):undefined;if(!asset){scene.add(new THREE.HemisphereLight(0xd9eaff,0x171b23,3));const key=new THREE.DirectionalLight(0xffffff,5);key.position.set(3,7,5);scene.add(key);const rim=new THREE.DirectionalLight(0xff763c,3);rim.position.set(-5,2,-3);scene.add(rim);}
 const engine=new THREE.Group();scene.add(engine);const materials={metal:new THREE.MeshStandardMaterial({color:0x969da1,metalness:.8,roughness:.35}),dark:new THREE.MeshStandardMaterial({color:0x272c33,metalness:.6,roughness:.5}),black:new THREE.MeshStandardMaterial({color:0x12161a,roughness:.65}),orange:new THREE.MeshStandardMaterial({color:0xf98145,metalness:.35,roughness:.3})};const pieces:THREE.Mesh[]=[];
 function box(w:number,h:number,d:number,x:number,y:number,z:number,mat:THREE.Material,name:string){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat.clone());m.position.set(x,y,z);m.userData={part:name,base:m.position.clone()};engine.add(m);pieces.push(m);return m;}
 function cylinder(r:number,h:number,x:number,y:number,z:number,mat:THREE.Material,name:string,front=false){const m=new THREE.Mesh(new THREE.CylinderGeometry(r,r,h,40),mat.clone());if(front)m.rotation.x=Math.PI/2;m.position.set(x,y,z);m.userData={part:name,base:m.position.clone()};engine.add(m);pieces.push(m);return m;}
 box(1.65,1.1,3.6,0,.65,0,materials.metal,'Engine block');box(1.8,.35,3.75,0,1.4,0,materials.metal,'Cylinder head');box(1.8,.28,3.3,0,-.03,0,materials.dark,'Oil pan');
 [-.48,.48].forEach(x=>{box(.66,.38,3.6,x,1.74,0,materials.dark,'Valve cover');for(let i=0;i<13;i++)box(.035,.025,3.3,x-.24+i*.04,1.944,0,materials.metal,'Valve cover');});
 for(let i=0;i<6;i++){const z=-1.4+i*.56;cylinder(.1,.08,0,1.7,z,materials.black,'Ignition');for(const x of [-.9,.9]){cylinder(.09,.09,x,1.63,z,materials.metal,'Cylinder head');}const c=new THREE.CatmullRomCurve3([new THREE.Vector3(.65,1.5,z),new THREE.Vector3(1.2,1.7,z),new THREE.Vector3(1.65,1.2,z),new THREE.Vector3(1.25,.85,z)]);const m=new THREE.Mesh(new THREE.TubeGeometry(c,20,.12,12,false),materials.metal);m.userData={part:'Intake manifold',base:m.position.clone()};engine.add(m);pieces.push(m);}
 box(.52,.6,3.3,1.4,.84,0,materials.metal,'Intake manifold');box(.34,.56,3.3,-1.03,.9,0,materials.dark,'Exhaust manifold');
 for(const x of [-.47,.47]){cylinder(.43,.15,x,1.48,1.97,materials.metal,'Camshaft sprockets',true);cylinder(.31,.17,x,1.48,2.01,materials.dark,'Camshaft sprockets',true);cylinder(.09,.2,x,1.48,2.03,materials.metal,'Camshaft sprockets',true);for(let i=0;i<36;i++){const a=i/36*Math.PI*2;const t=box(.052,.068,.15,x+Math.cos(a)*.43,1.48+Math.sin(a)*.43,1.98,materials.metal,'Camshaft sprockets');t.rotation.z=a;}}
 cylinder(.48,.3,0,.22,2.02,materials.dark,'Crankshaft pulley',true);cylinder(.32,.32,0,.22,2.05,materials.metal,'Crankshaft pulley',true);cylinder(.12,.34,0,.22,2.08,materials.dark,'Crankshaft pulley',true);cylinder(.24,.22,.62,.75,2.02,materials.orange,'Water pump',true);cylinder(.17,.2,-.57,.64,2.05,materials.metal,'Tensioner',true);
 const path=new THREE.CatmullRomCurve3([[-.85,1.52,2.01],[-.48,1.9,2.01],[.48,1.9,2.01],[.87,1.52,2.01],[.48,.2,2.01],[0,-.2,2.01],[-.47,.18,2.01],[-.85,1.52,2.01]].map(p=>new THREE.Vector3(...p as [number,number,number])),true,'catmullrom',.1);const belt=new THREE.Mesh(new THREE.TubeGeometry(path,100,.055,8,true),materials.orange.clone());belt.userData={part:'Timing belt',base: new THREE.Vector3()};engine.add(belt);pieces.push(belt);
 for(let i=0;i<8;i++)box(1.72,.04,3.62,0,.3+i*.1,0,materials.dark,'Engine block');
 const coverMaterial=new THREE.MeshStandardMaterial({color:0x242c36,metalness:.35,roughness:.6});
 const cover=box(1.85,2.1,.2,0,.88,2.29,coverMaterial,'Timing covers');cover.visible=false;
 const car=new THREE.Group();scene.add(car);const shell=new THREE.MeshStandardMaterial({color:0x5b6b79,metalness:.8,roughness:.28});const glass=new THREE.MeshStandardMaterial({color:0x182431,metalness:.7,roughness:.1});
 function carBox(w:number,h:number,d:number,x:number,y:number,z:number,mat:THREE.Material){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat);m.position.set(x,y,z);car.add(m);return m;}
 carBox(3.5,.35,8.5,0,-.3,0,shell);carBox(.2,1,8.3,-1.75,.32,0,shell);carBox(.2,1,8.3,1.75,.32,0,shell);carBox(3.3,.75,2.1,0,.28,-3.05,shell);carBox(3.1,.9,2.9,0,.85,-1,glass);carBox(3.2,.12,2.7,0,1.35,-1,shell);carBox(3.45,.6,.15,0,.25,4.22,shell);for(const x of [-1.8,1.8])for(const z of [-2.8,2.8]){const tire=new THREE.Mesh(new THREE.CylinderGeometry(.72,.72,.36,32),materials.black);tire.rotation.z=Math.PI/2;tire.position.set(x,-.03,z);car.add(tire);const wheel=new THREE.Mesh(new THREE.CylinderGeometry(.47,.47,.38,24),materials.metal);wheel.rotation.z=Math.PI/2;wheel.position.copy(tire.position);car.add(wheel);}for(const x of [-1.2,1.2])carBox(.7,.25,.05,x,.56,4.32,new THREE.MeshStandardMaterial({color:0xc6dcf0,emissive:0x617386,emissiveIntensity:.5}));
 const hoodGroup=new THREE.Group();hoodGroup.position.set(0,1.3,.52);car.add(hoodGroup);const hoodPanel=new THREE.Mesh(new THREE.BoxGeometry(3.2,.1,3.6),shell);hoodPanel.position.z=1.8;hoodGroup.add(hoodPanel);car.visible=false;
 const grid=new THREE.GridHelper(24,48,0x39424a,0x242b32);grid.position.y=-.8;scene.add(grid);engine.rotation.y=-.12;
 let alive=true;let frame=0;let custom:THREE.Group|undefined;
 const draw=()=>{frame=0;if(!alive)return;controls.update();renderer.render(scene,camera);};const invalidate=()=>{if(!frame&&alive)frame=requestAnimationFrame(draw);};controls.addEventListener('change',invalidate);invalidate();
 const resize=new ResizeObserver(()=>{if(!alive||!resizePerspective(camera,el.clientWidth,el.clientHeight))return;renderer.setSize(el.clientWidth,el.clientHeight);invalidate()});resize.observe(el);
 let down={x:0,y:0};const pointerDown=(e:PointerEvent)=>{down={x:e.clientX,y:e.clientY}};const pointerUp=(e:PointerEvent)=>{if(Math.hypot(e.clientX-down.x,e.clientY-down.y)>5)return;const rect=renderer.domElement.getBoundingClientRect();const ray=new THREE.Raycaster();ray.setFromCamera(new THREE.Vector2((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1),camera);const target=ray.intersectObjects(custom?[custom]:[engine],true).find(isVisibleModelHit);if(target)selectRef.current?.(target.object.userData.part||target.object.name||'Unnamed mesh');};renderer.domElement.addEventListener('pointerdown',pointerDown);renderer.domElement.addEventListener('pointerup',pointerUp);
 const keyDown=(e:KeyboardEvent)=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','-'].includes(e.key))return;e.preventDefault();const offset=camera.position.clone().sub(controls.target);if(e.key==='+'||e.key==='-')offset.multiplyScalar(e.key==='+'?.9:1.1);else{const sph=new THREE.Spherical().setFromVector3(offset);sph.theta+=(e.key==='ArrowLeft'?.12:e.key==='ArrowRight'?-.12:0);sph.phi=Math.max(.2,Math.min(Math.PI-.2,sph.phi+(e.key==='ArrowUp'?-.12:e.key==='ArrowDown'?.12:0)));offset.setFromSpherical(sph);}camera.position.copy(controls.target).add(offset);controls.update();invalidate();};el.addEventListener('keydown',keyDown);
 const contextLost=(event:Event)=>{event.preventDefault();if(alive)setError('The graphics session was interrupted. Waiting for the browser to restore the 3D view; reload if it does not recover.');};const contextRestored=()=>{if(alive){setError(previous=>previous.startsWith('The graphics session was interrupted.')?'':previous);invalidate();}};renderer.domElement.addEventListener('webglcontextlost',contextLost);renderer.domElement.addEventListener('webglcontextrestored',contextRestored);
 refs.current={engine,pieces,controls,camera,car,hoodGroup,cover,invalidate,highlight:createMaterialHighlighter()};
 if(asset){engine.visible=false;setLoading(true);setError('');new GLTFLoader().setMeshoptDecoder(MeshoptDecoder).load(asset,gltf=>{if(!alive){disposeViewerResources(gltf.scene);return;}custom=gltf.scene;const bounds=new THREE.Box3().setFromObject(custom);const size=bounds.getSize(new THREE.Vector3());const length=Math.max(size.x,size.y,size.z);if(!length||!Number.isFinite(length)){disposeViewerResources(custom);custom=undefined;setError('This model has no visible geometry.');setLoading(false);return;}const center=bounds.getCenter(new THREE.Vector3());custom.position.sub(center);const wrapper=new THREE.Group();wrapper.add(custom);wrapper.scale.setScalar(4.5/length);wrapper.position.y=.8;scene.add(wrapper);setLoading(false);invalidate();},undefined,()=>{if(alive){setError('This model could not be displayed. Try an uncompressed GLB with embedded textures.');setLoading(false);}});}
 return()=>{alive=false;cancelAnimationFrame(frame);resize.disconnect();controls.dispose();el.removeEventListener('keydown',keyDown);renderer.domElement.removeEventListener('pointerdown',pointerDown);renderer.domElement.removeEventListener('pointerup',pointerUp);renderer.domElement.removeEventListener('webglcontextlost',contextLost);renderer.domElement.removeEventListener('webglcontextrestored',contextRestored);disposeViewerResources(scene,[...Object.values(materials),coverMaterial]);refs.current=null;environment?.dispose();renderer.dispose();el.replaceChildren();};
 },[asset]);
 useEffect(()=>{const r=refs.current;if(!r)return;r.car.visible=mode==='vehicle'&&!asset;r.engine.scale.setScalar(mode==='vehicle'?.65:1);r.engine.position.set(0,0,mode==='vehicle'?2.2:0);r.hoodGroup.rotation.x=hood?-.95:0;r.cover.visible=covers&&!asset;r.pieces.forEach((p:THREE.Mesh)=>{p.position.copy(p.userData.base);const part=p.userData.part;if(exploded){if(part==='Valve cover')p.position.y+=.8;if(part==='Cylinder head')p.position.y+=.4;if(['Timing belt','Water pump','Camshaft sprockets','Crankshaft pulley','Tensioner','Timing covers'].includes(part))p.position.z+=.8;}for(const material of Array.isArray(p.material)?p.material:[p.material])r.highlight(material,part===selected,0xff793b,.55);});r.invalidate();},[exploded,step,mode,hood,covers,selected,asset]);
 useEffect(()=>{const r=refs.current;if(r){r.camera.position.set(mode==='vehicle'?11:7,mode==='vehicle'?8:5.4,mode==='vehicle'?13:8);r.controls.target.set(0,.8,0);r.controls.update();r.invalidate();}},[reset,mode,asset]);return <><div className="three-host" ref={host} tabIndex={0} role="img" aria-label={(asset?'Imported 3D model. ':'Illustrative engine. ')+'Drag to rotate, scroll to zoom, or focus and use arrow keys and plus or minus.'}/>{(error||loading)&&<div className="renderer-message" role="status">{error||'Loading your 3D model…'}</div>}</>;
}
