export type ServiceStudy={id:string;topic:string;title:string;summary:string;reference:string;sourceIds:string[];visible:string[];camera:string;focus:string[];hidden:string[];parts:string[];offsets?:Record<string,[number,number,number]>;limit:string};
const covers=['oil-cap','engine-cover','engine-cover-lettering','timing-cover-top','timing-cover-upper','timing-cover-lower'];
const drive=['accessory-belt','water-pump-pulley','pump-pulley-lip','crank-damper','crank-damper-bolt','accessory-tensioner','accessory-tensioner-arm','accessory-tensioner-pulley'];
const coverBolts=[...Array.from({length:3},(_,i)=>'timing-cover-upper-bolt-'+(i+1)),...Array.from({length:5},(_,i)=>'timing-cover-lower-bolt-'+(i+1)),...Array.from({length:4},(_,i)=>'timing-cover-top-bolt-'+(i+1)),...Array.from({length:4},(_,i)=>'engine-cover-nut-'+(i+1))];
const pulleyNuts=Array.from({length:4},(_,i)=>'water-pump-pulley-nut-'+(i+1));
const engine=['engine','intake','electrical','cooling','exhaust'];
const timing=['exhaust-cam-sprocket','vvti-gear','crank-pulley','timing-belt','timing-idler','timing-tensioner'];
const trans=['transmission'];
const panBolts=Array.from({length:19},(_,i)=>'trans-pan-bolt-'+(i+1));
const strainerBolts=Array.from({length:4},(_,i)=>'trans-strainer-bolt-'+(i+1));
const pan=['transmission-pan','trans-pan-sealant','trans-drain-plug','trans-drain-washer',...panBolts,...Array.from({length:3},(_,i)=>'trans-pan-magnet-'+(i+1))];
const strainer=['trans-strainer',...strainerBolts,...Array.from({length:3},(_,i)=>'trans-strainer-seal-'+(i+1))];
const removeTiming=[...covers,...coverBolts,...drive,...pulleyNuts];
export const serviceStudies:ServiceStudy[]=[
 {id:'air-intake',topic:'Engine bay',title:'Air duct, bellows & MAF',summary:'Follow the curved air duct from the air cleaner toward the throttle body. The flexible bellows and clamp bands now follow the duct surface; the meter housing and connector can be selected separately.',reference:'2000 GS300 engine-bay photograph · intake surface revision, October 2026',sourceIds:['gs300-engine-photo'],visible:['intake','electrical','engine'],camera:'intake',focus:['air-intake-duct','intake-bellows','intake-clamps','maf'],hidden:[],parts:['air-intake-duct','intake-bellows','intake-clamps','maf','maf-connector','airbox','throttle'],limit:'Photo-informed shapes with inherited installation endpoints. Diameters, ridge count, connector details and mounting dimensions remain estimates; this is an anatomy view, not a removal procedure.'},
 {id:'engine-layout',topic:'2JZ-GE',title:'Stock engine layout',summary:'Follow the intake crossover to the right-side airbox. The front appearance cover, rear intake connector, VVT-i oil supply and accessory drive are separate selectable groups.',reference:'2000 GS300 photograph + RM718U EM cylinder-head diagrams',sourceIds:['gs300-engine-photo','rm718u-engine'],visible:engine,camera:'engine',focus:['engine-block','intake-crossover','airbox','radiator'],hidden:[],parts:['intake-crossover','throttle','airbox','vvti-oil-control-valve','water-pump-pulley'],limit:'Photographs establish arrangement, not hidden casting dimensions or exact clearances.'},
 {id:'timing-covers',topic:'Timing',title:'Timing cover layers',summary:'Inspect the three removable cover groups and their fasteners. The rear cover remains behind the cam pulleys. This view separates the protective layers for inspection.',reference:'RM718U EM timing-belt components',sourceIds:['rm718u-timing'],visible:['engine'],camera:'timing',focus:timing,hidden:['oil-cap','engine-cover','engine-cover-lettering',...coverBolts,...drive],offsets:{'timing-cover-upper':[0,.07,.17],'timing-cover-lower':[0,-.05,.19],'timing-cover-top':[0,.20,0]},parts:['timing-cover-upper','timing-cover-lower','timing-cover-top','timing-cover-rear'],limit:'Cover bolt counts are documented; modeled hole coordinates and removal paths are estimates.'},
 {id:'timing-drive',topic:'Timing',title:'Belt, idler and hydraulic tensioner',summary:'The timing idler and hydraulic tensioner are different parts. Inspect their relationship with the crank and cam pulleys, including the larger VVT-i intake assembly.',reference:'RM718U EM timing-belt components',sourceIds:['rm718u-timing'],visible:['engine'],camera:'timing',focus:timing,hidden:removeTiming,parts:['timing-belt','timing-idler','timing-tensioner','timing-tensioner-rod','vvti-gear'],limit:'Routing is a study. Do not use these meshes for timing alignment, tooth counting or belt-tension decisions.'},
 {id:'vvti',topic:'Timing',title:'VVT-i oil-control hardware',summary:'Follow the external oil pipe from the filter housing to the cam area. The oil-control valve and its connector are individually selectable.',reference:'RM718U EM-30/31',sourceIds:['rm718u-engine','rm718u-timing'],visible:['engine','electrical'],camera:'engine',focus:['vvti-gear','vvti-oil-control-valve','vvti-oil-pipe'],hidden:[...covers,...coverBolts],parts:['vvti-oil-control-valve','vvti-ocv-connector','vvti-oil-pipe','vvti-oil-filter','vvti-gear-locked-fasteners'],limit:'The five factory-set pulley bolts are not service-removal targets. Internal oil passages are not validated.'},
 {id:'pump-drive',topic:'Cooling',title:'Water-pump drive and mounting',summary:'The water pump has its own accessory pulley. The drawing identifies four pulley nuts and six pump-to-block bolts; these are separate from the timing idler and tensioner.',reference:'RM718U CO-5–8',sourceIds:['rm718u-pump'],visible:['engine','cooling'],camera:'pump',focus:['water-pump','water-pump-pulley','water-inlet'],hidden:['engine-cover','engine-cover-lettering','accessory-belt','timing-cover-upper','timing-cover-lower'],offsets:{'water-pump-pulley':[0,0,.15],'pump-pulley-lip':[0,0,.15],...Object.fromEntries(pulleyNuts.map(id=>[id,[0,0,.15] as [number,number,number]]))},parts:['water-pump','water-pump-pulley','water-pump-bolt-1','water-pump-pulley-nut-1'],limit:'The pulley is separated for inspection. This is not a complete pump-removal sequence.'},
 {id:'pump-seals',topic:'Cooling',title:'Pump seals, inlet and bypass',summary:'Inspect the gasket, block O-ring, drain hose, thermostat and two bypass pipes as distinct components.',reference:'RM718U CO water-pump components',sourceIds:['rm718u-pump'],visible:['cooling'],camera:'pump',focus:['water-pump','water-pump-gasket','water-inlet','thermostat'],hidden:['water-pump-pulley','pump-pulley-lip',...pulleyNuts],offsets:{'water-pump':[0,0,.16],'water-pump-hub':[0,0,.16],'pump-impeller':[0,0,.16],'water-pump-gasket':[0,0,.08],'thermostat':[.10,0,0],'thermostat-seal':[.15,0,0],'water-inlet':[.22,0,0]},parts:['water-pump-gasket','pump-block-oring','water-pump-drain','thermostat','water-bypass-pipe-1','water-bypass-pipe-2'],limit:'Seal outlines, impeller shape and port dimensions still require measurement.'},
 {id:'trans-case',topic:'A650E',title:'Transmission case and connections',summary:'Explore the converter housing, ribbed main case and extension housing. Find the range switch, cooler pipes, speed sensors, breather and dipstick tube.',reference:'Transtar A650E exploded parts plate + GS300 A/T service',sourceIds:['transtar-a650e','rm718u-at-service'],visible:trans,camera:'transmission',focus:['bellhousing','transmission-case','tail-housing'],hidden:[],parts:['bellhousing','transmission-case','tail-housing','range-switch','atf-cooler-line-1','atf-dipstick-tube'],limit:'A650E-family construction is represented; exact GS300 casting and installation dimensions remain unverified.'},
 {id:'trans-pan',topic:'A650E',title:'Pan and magnets',summary:'Separate the pan to expose the strainer. The GS300 service reference identifies nineteen pan bolts and three magnets. The sealing bead represents FIPG.',reference:'2000 GS300 AT pan/temperature-sensor service',sourceIds:['rm718u-at-service'],visible:trans,camera:'transmission-service',focus:['transmission-case','transmission-pan'],hidden:[],offsets:Object.fromEntries(pan.map(id=>[id,[0,-.18,0] as [number,number,number]])),parts:['transmission-pan','trans-pan-magnet-1','trans-pan-sealant','trans-drain-plug','trans-strainer'],limit:'Bolt lengths, torque application, drain/fill procedure and fluid-level checks are not supplied by this study.'},
 {id:'trans-strainer',topic:'A650E',title:'Strainer and seals',summary:'The strainer has four retaining bolts and three seals. Separate it from the valve-body stack to inspect its connections.',reference:'2000 GS300 AT strainer service',sourceIds:['rm718u-at-service'],visible:trans,camera:'transmission-service',focus:['valve-body','trans-strainer'],hidden:[...pan,'trans-pan-flange'],offsets:Object.fromEntries(strainer.map(id=>[id,[0,-.13,0] as [number,number,number]])),parts:['trans-strainer','trans-strainer-seal-1','trans-strainer-seal-2','trans-strainer-seal-3','trans-temperature-sensor'],limit:'The pickup and seal seats are estimated; this model cannot verify sealing fit.'},
 {id:'trans-valve-body',topic:'A650E',title:'Valve body and seven solenoids',summary:'Inspect the three cast sections, wiring and temperature sensor. The seven solenoids are labeled individually using the A650E-family overhaul reference.',reference:'RM718U AT-8 + adjacent-year A650E overhaul',sourceIds:['rm718u-at-valve','rm718u-at-service','a650e-valve-overhaul'],visible:trans,camera:'transmission-service',focus:['valve-body','valve-body-lower-1','valve-body-lower-2'],hidden:[...pan,...strainer,'trans-pan-flange'],parts:['valve-body','valve-body-lower-1','solenoid-s1','solenoid-sln','solenoid-slu','solenoid-slt','trans-solenoid-harness'],limit:'Channels, valve placement, connector pinouts and calibration are not validated; this is not a valve-body rebuilding guide.'},
 {id:'trans-internals',topic:'A650E',title:'Internal component study',summary:'Remove the case shells to inspect representative clutch drums, friction and steel plates, planetary sets and front pump.',reference:'Transtar A650E family exploded parts plate',sourceIds:['transtar-a650e'],visible:trans,camera:'transmission',focus:['front-pump','trans-output-shaft'],hidden:['bellhousing','bellhousing-flange','bellhousing-fasteners','transmission-case','case-ribs','case-longitudinal-ribs','tail-housing','tail-ribs','torque-converter','converter-weld',...pan,'trans-pan-flange'],parts:['front-pump','direct-clutch-drum','forward-clutch-frictions','planetary-sun-1','trans-input-shaft'],limit:'Representative geometry only: clutch quantities, gear tooth counts, stack order and operating clearances are unverified.'}
];

const radiatorParts=['radiator','radiator-fins','radiator-tanks','fan-shroud','fan-motor--1','fan-motor-1','fan-blades--1','fan-blades-1','fan-wiring','condenser','receiver-drier','radiator-cap','radiator-cushions','radiator-drain','upper-radiator-hose','lower-radiator-hose','coolant-reservoir','reservoir-cap','coolant-overflow'];
for(const s of serviceStudies){if(s.id.startsWith('pump-'))s.hidden.push(...radiatorParts);}
const rearSystems=['fuel-tank','fuel-pump-module','tank-strap--1','tank-strap-1','fuel-line','filler-neck',...['left','right'].flatMap(side=>['exhaust-tip-','exhaust-tip-dark-','exhaust-pipe-','catalyst-','muffler-','exhaust-hanger-'].map(prefix=>prefix+side))];
for(const s of serviceStudies){if(!s.id.startsWith('trans-'))s.hidden.push(...rearSystems);}
