export const vehicles=[{id:'gs300',name:'GS 300',type:'Sport sedan',detail:'2000 · 2JZ-GE',available:true},{id:'gs400',name:'GS 400',type:'Sport sedan',detail:'Model needed'},{id:'gs430',name:'GS 430',type:'Sport sedan',detail:'Model needed'},{id:'ls400',name:'LS 400',type:'Flagship sedan',detail:'Model needed'},{id:'ls430',name:'LS 430',type:'Flagship sedan',detail:'Model needed'},{id:'es300',name:'ES 300',type:'Executive sedan',detail:'Model needed'},{id:'es330',name:'ES 330',type:'Executive sedan',detail:'Model needed'},{id:'rx300',name:'RX 300',type:'SUV',detail:'Model needed'},{id:'rx330',name:'RX 330',type:'SUV',detail:'Model needed'},{id:'gx470',name:'GX 470',type:'SUV',detail:'Model needed'},{id:'lx470',name:'LX 470',type:'SUV',detail:'Model needed'}];
export const chapters=[
 {title:'Explore the engine bay',short:'Engine anatomy',part:'Engine block',body:'Start with the layout. Rotate the model to see the cylinder head, intake runners, and the front of the engine. This is a simplified inline-six assembly, not dimensionally accurate 2JZ-GE geometry.',tip:'Select a visible part to identify it.'},
 {title:'Identify the timing covers',short:'The protective layer',part:'Timing covers',body:'Timing covers shield the timing assembly. Use the cover control to reveal the belt and pulleys beneath. These covers demonstrate the relationship between layers; actual fasteners and removal order are not modeled.',tip:'Toggle covers to see what sits underneath.'},
 {title:'Trace the timing belt',short:'A synchronized system',part:'Timing belt',body:'The belt connects the crankshaft and camshaft sprockets. Follow the highlighted loop to understand that relationship. Its routing, timing marks, and tooth counts here are illustrative.',tip:'Timing alignment must come from the correct factory repair manual.'},
 {title:'Locate the water pump',short:'The cooling system',part:'Water pump',body:'Find the highlighted pump near the timing assembly. The simplified model shows its relationship to surrounding components. Its housing, drive arrangement, seals, and mounting details need model-specific verification.',tip:'Use the exact vehicle and engine variant when checking replacement parts.'},
 {title:'Inspect the tensioner',short:'Keeping the belt controlled',part:'Tensioner',body:'Locate the tensioner beside the belt. This chapter introduces the component only. Compression method, installation, tension settings, and service limits require verified service documentation.',tip:'Use exploded view to separate overlapping components.'},
 {title:'Review the assembly',short:'Put the picture together',part:'Engine block',body:'Return to the assembled view and review how the parts relate. You have completed a layout exploration, not a repair qualification. A complete repair guide still needs validated geometry, fasteners, specifications, and expert review.',tip:'Contribute a model or leave a question to help develop this workshop.'}
];
export type ModelRecord={id:string;vehicle:string;name:string;fitment:string;source:string;license:string;size:number;created_at:number};
export type CommentRecord={id:string;chapter:number;author:string;body:string;created_at:number};
