import {lazy,Suspense} from 'react';
import {createRoot} from 'react-dom/client';
import {appPath} from '../lib/app-path';
import '../app/globals.css';
const Home=lazy(()=>import('../app/page'));
const Catalog=lazy(()=>import('../app/catalog/page'));
const Assembly=lazy(()=>import('../app/assembly/page'));
const Components=lazy(()=>import('../app/components/page'));
const Research=lazy(()=>import('../app/research/page'));
const base=appPath('/');
const route=location.pathname.slice(base.length).replace(/\/$/,'');
const routes:Record<string,typeof Home>={'':Home,catalog:Catalog,assembly:Assembly,components:Components,research:Research};
const Page=routes[route];
createRoot(document.getElementById('root')!).render(<Suspense fallback={<main aria-busy="true">Loading workshop…</main>}>{Page?<Page/>:<main><h1>Page not found</h1><a href={base}>Open the workshop</a></main>}</Suspense>);
