import {lazy,Suspense} from 'react';
import type {Root} from 'react-dom/client';
type HotContext={data:{root?:Root};dispose:(callback:(data:{root?:Root})=>void)=>void};
import {createRoot} from 'react-dom/client';
import {appPath} from '../lib/app-path';
import LoadingBoundary from '../components/loading-boundary';
import '../app/globals.css';
const Home=lazy(()=>import('../app/page'));
const Catalog=lazy(()=>import('../app/catalog/page'));
const Assembly=lazy(()=>import('../app/assembly/page'));
const Components=lazy(()=>import('../app/components/page'));
const Library=lazy(()=>import('../app/library/page'));
const Research=lazy(()=>import('../app/research/page'));
const base=appPath('/');
const route=location.pathname.slice(base.length).replace(/\/$/,'');
const routes:Record<string,typeof Home>={'':Home,catalog:Catalog,assembly:Assembly,components:Components,research:Research,library:Library};
const Page=routes[route];
const hot = (import.meta as ImportMeta & {hot?:HotContext}).hot;
const root = hot?.data.root ?? createRoot(document.getElementById('root')!);
if (hot) hot.dispose(data => {data.root = root;});
root.render(<LoadingBoundary><Suspense fallback={<main aria-busy="true">Loading workshop…</main>}>{Page?<Page/>:<main><h1>Page not found</h1><a href={base}>Open the workshop</a></main>}</Suspense></LoadingBoundary>);
