import audit from '@/research/vehicle-sources.json';
import licenses from '@/research/asset-licenses.json';
import {Wrench,ChevronLeft,ExternalLink} from 'lucide-react';
import '../assembly/assembly.css';
const ready=new Set(['gs300','gs400','gs430','rx300']);
const label=(id:string)=>id.replace(/([a-z]+)(\d+)/,'$1 $2').toUpperCase();
const status=(value:string)=>({'missing':'Missing','perspective-only':'Oblique only','photographic-view':'Photo found','photographic-side-view':'Photo found','oblique-roof-only':'Roof angle only','side-candidates-awaiting-handedness-review':'Needs review'}[value]||value);
export default function ResearchPage(){return <div className="assembly-app"><header className="assembly-header"><a className="brand" href="/"><span className="brand-mark"><Wrench size={21}/></span>wrenchwise<span className="alpha">ALPHA</span></a><a className="back-workshop" href="/assembly"><ChevronLeft size={15}/>GS 300 assembly</a></header><main className="assembly-main"><div className="assembly-heading"><div><div className="eyebrow orange">VEHICLE GEOMETRY / SOURCE AUDIT</div><h1>Evidence for every Lexus.</h1><p>11 catalog entries · 230 OEM photo records · 228 distinct image files · 2 acquired source meshes</p></div></div><div className="accuracy-banner"><span><strong>The full catalog is not complete.</strong> Four exterior references are available from two acquired meshes. No model is approved as a 1:1 or repair-grade replica, and no complete set of six OEM views has been found.</span></div>
<p>The confirmed GS 300 target is a stock US-market 2000 automatic; mesh fitment remains unverified. The other model years below are working targets. Canadian manufacturer photos help establish body shape; US equipment and adjacent-year differences remain explicit. “Photo found” means a photographic view, not a calibrated blueprint.</p>
<div style={{overflowX:'auto',margin:'24px 0'}}><table style={{width:'100%',borderCollapse:'collapse',fontSize:14}}><thead><tr>{['Vehicle target','Photos','Front','Rear','Left','Right','Top','Underbody','Geometry'].map(x=><th key={x} style={{textAlign:'left',padding:12,borderBottom:'1px solid #38424b'}}>{x}</th>)}</tr></thead><tbody>{audit.vehicles.map(v=><tr key={v.vehicle}><td style={{padding:12}}><a href={'#'+v.vehicle}>{v.targetYear} {label(v.vehicle)}</a></td><td>{v.photos.length}</td>{Object.values(v.sixViewCoverage).map((c,i)=><td key={i} style={{padding:8,color:c.status==='missing'?'#eeac83':undefined}}>{status(c.status)}</td>)}<td>{ready.has(v.vehicle)?'Exterior reference':'Not accepted'}</td></tr>)}</tbody></table></div>
<p><a className="evidence-link" href="/research/vehicle-sources.json" download>Download the complete photo and model source ledger</a><a className="evidence-link" href="https://github.com/Zhandolia/wrenchwise" target="_blank" rel="noreferrer">Source code and modeling history <ExternalLink size={14}/></a></p>
<div className="research-grid">{audit.vehicles.map(v=><article id={v.vehicle} key={v.vehicle}><span className="source-chip">{v.targetYear} · US TARGET</span><h2>Lexus {label(v.vehicle)}</h2><p>{v.engine} · {v.drivetrain}</p>{ready.has(v.vehicle)&&<><img src={'/models/catalog/'+v.vehicle+'-perspective.png'} alt={label(v.vehicle)+' adapted exterior reference, unverified'} style={{width:'100%',borderRadius:8}}/><p><a className="evidence-link" href={v.vehicle==='gs300'?'/assembly':'/?vehicle='+v.vehicle}>Explore reference geometry →</a><a className="evidence-link" href={'/models/catalog/'+v.vehicle+'-reference.glb'} download>Download CC BY exterior GLB</a></p><small>Source mesh: David_Holiday · CC BY 4.0. Wrenchwise materials and trim adaptations. GS 400/430 use the GS body source; exact variant details remain unverified.</small></>}
<p>{v.photoYearNote}. {v.photos.length} photo records inspected. {v.photos.filter(p=>p.view.startsWith('wrong')).length} wrong-vehicle/engine images excluded.</p><a className="evidence-link" href={v.albumUrl} target="_blank" rel="noreferrer">Lexus manufacturer photo album <ExternalLink size={14}/></a><a className="evidence-link" href={v.specificationSource} target="_blank" rel="noreferrer">Archived manufacturer specifications <ExternalLink size={14}/></a><p>Envelope targets: {v.dimensions.lengthIn} × {v.dimensions.bodyWidthIn} × {v.dimensions.heightIn} in. Wheelbase: {v.dimensions.wheelbaseIn} in. These targets do not validate the surface geometry.</p><h3>3D model search</h3>{v.modelCandidates.map(m=><div key={m.url} style={{marginBottom:18}}><a className="evidence-link" href={m.url} target="_blank" rel="noreferrer">{m.status.replaceAll('-',' ')} · {m.license}<ExternalLink size={14}/></a><p>{m.fitmentNote}</p></div>)}</article>)}</div>
<section className="validation-layout" style={{marginTop:24}}><div><h2>Errors caught during review</h2><ul><li>The 2000 LX 470 album contains an RX 300 side photo.</li><li>The LS 400 and LS 430 albums contain a GS interior photo.</li><li>The ES 330 album includes an ES 300 badge and a 3.0-liter engine image. Uncertain facelift/interior photos are quarantined.</li><li>The original GS mesh included an optional spoiler. It was removed; materials and grille finish were revised.</li><li>A new procedural LS 400 trial failed two visual reviews and was excluded from the catalog.</li></ul></div><div><h2>What is still needed</h2><p>Seven entries still lack accepted model geometry. The LS 430 mesh and ES 300 / RX 330 scans require a Sketchfab login to download. Other candidates have generation, modification, licensing, or completeness limitations.</p><p>Factory top and underbody views, exact wheel/trim identification, measured mechanical parts, fastener mapping and service procedure review are still outstanding. Exterior photographs cannot establish the internal engine or transmission geometry.</p></div></section>
<section style={{marginTop:24}}><h2>Asset attribution</h2>{licenses.map(a=><p key={a.vehicle}><a href={a.sourceUrl} target="_blank" rel="noreferrer">{a.title}</a> by <a href={a.authorUrl} target="_blank" rel="noreferrer">{a.author}</a> · <a href={a.licenseUrl} target="_blank" rel="noreferrer">{a.license}</a>. Modified for Wrenchwise; no endorsement implied.</p>)}<p>Manufacturer photos are linked for reference and are not redistributed as MIT or CC BY assets.</p></section></main></div>}
