'use client';
import {appPath} from '@/lib/app-path';
import {versionS160Asset} from '@/lib/s160-assets';
import { useEffect,useState } from 'react';
import { Wrench,Layers,RotateCcw,Search,Box,Download,ExternalLink,ChevronLeft,Eye,CarFront,ShieldAlert,Check,ChevronDown } from 'lucide-react';
import { Checkbox } from '@/components/ui/checkbox';
import { Slider } from '@/components/ui/slider';
import { Tabs,TabsList,TabsTrigger,TabsContent } from '@/components/ui/tabs';
import { Input } from '@/components/ui/input';
import { Select,SelectTrigger,SelectValue,SelectContent,SelectItem } from '@/components/ui/select';
import AssemblyViewer from '@/components/assembly-viewer';
import GuidedLesson from '@/components/guided-lesson';
import MechanicalWorkspace from '@/components/mechanical-workspace';
import './assembly.css';
import {serviceStudies} from '@/lib/s160-service';
import {evidenceCounts, type VehicleEvidence} from '@/lib/vehicle-evidence';
type Part={id:string;name:string;system:string;status:string;notes:string;accuracy:string;dimensionsMetres?:number[];source:string;sourceRefs?:string[];quantityEvidence?:{count:number;section:string;scope:string}};
type Manifest={title:string;systems:Record<string,string>;parts:Part[];meshCount:number;triangleCount:number;openIssues:string[];sources:{id:string;title:string;url:string}[];dimensionTargets:{lengthMetres:number;bodyWidthMetres:number;heightMetres:number;wheelbaseMetres:number;basis:string}};
export default function AssemblyPage(){
 const params=typeof window==='undefined'?new URLSearchParams():new URLSearchParams(window.location.search);
 return params.get('lesson')==='timing-belt'||(!params.has('study')&&!params.has('lesson'))?<MechanicalWorkspace/>:<AssemblyExplorer/>;
}
function AssemblyExplorer(){const [learning,setLearning]=useState(()=>typeof window==='undefined'||!new URLSearchParams(window.location.search).has('study'));const [evidence,setEvidence]=useState<VehicleEvidence|null>(null);const [evidenceError,setEvidenceError]=useState('');const [data,setData]=useState<Manifest|null>(null),[error,setError]=useState(''),[visible,setVisible]=useState<string[]>([]),[selected,setSelected]=useState<string|null>(null),[explode,setExplode]=useState(0),[cutaway,setCutaway]=useState(false),[view,setView]=useState('vehicle'),[reset,setReset]=useState(0),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[systemFilter,setSystemFilter]=useState('all'),[bottomTab,setBottomTab]=useState('inventory'),[studyId,setStudyId]=useState<string|null>(null);
 const study=serviceStudies.find(s=>s.id===studyId);
 const selectStudy=(id:string)=>{const s=serviceStudies.find(s=>s.id===id);if(!s)return;setStudyId(id);setVisible(s.visible);setView(s.camera);setSelected(id==='under-hood'?null:s.parts[0]);setExplode(0);setCutaway(false);setReset(r=>r+1)};
 useEffect(()=>{fetch(appPath(versionS160Asset('/models/gs300-parts.json'))).then(async r=>{if(!r.ok)throw new Error('The assembly index could not be loaded.');const j=await r.json() as Manifest;setData(j);setVisible(Object.keys(j.systems));const initial=new URLSearchParams(window.location.search).get('study');if(initial)selectStudy(initial)}).catch(e=>setError(e.message))},[]);
 useEffect(()=>{fetch(appPath(versionS160Asset('/models/gs300-evidence.json'))).then(async r=>{if(!r.ok)throw new Error('Evidence records are unavailable.');setEvidence(await r.json())}).catch(e=>setEvidenceError(e.message))},[]);
 const reviewed=evidence?.records.find(p=>p.id===selected);const counts=evidence?evidenceCounts(evidence):null;
 const part=data?.parts.find(p=>p.id===selected);const modeled=data?.parts.filter(p=>p.status==='modeled').length||0;const missing=data?.parts.filter(p=>p.status==='missing').length||0;const shown=data?.parts.filter(p=>(filter==='all'||(filter==='modeled'?p.status==='modeled':filter==='missing'?evidence?.records.find(r=>r.id===p.id)?.geometry==='absent':['partial','unresolved'].includes(evidence?.records.find(r=>r.id===p.id)?.geometry||'')))&&(systemFilter==='all'||p.system===systemFilter)&&(p.name+' '+p.id+' '+data.systems[p.system]).toLowerCase().includes(query.toLowerCase()))||[];
 const choose=(id:string)=>{setSelected(id);setStudyId(current=>{const s=serviceStudies.find(s=>s.id===current);return s&&(s.hidden.includes(id)||(s.only&&!s.only.includes(id)))?null:current});const p=data?.parts.find(p=>p.id===id);if(p&&p.status==='modeled'){setVisible(v=>v.includes(p.system)?v:[...v,p.system]);setCutaway(false);}};
 const showView=(v:string)=>{if(v==='engine'){selectStudy('under-hood');return;}setStudyId(null);setView(v);setExplode(0);if(v==='engine')setVisible(['engine','intake','electrical','cooling']);else if(v==='transmission')setVisible(['transmission']);else if(v==='underbody')setVisible(Object.keys(data?.systems||{}).filter(k=>!['body','interior'].includes(k)));else setVisible(Object.keys(data?.systems||{}));setReset(r=>r+1)};
 useEffect(()=>{const ctx=(document as any).modelContext;if(!ctx?.registerTool||!data)return;const life=new AbortController();const tools=[{name:'get_vehicle_inventory',description:'Read GS300 inventory with legacy status, geometry coverage and independent evidence states. No part is mechanically verified.',inputSchema:{type:'object',properties:{system:{type:'string'},status:{enum:['all','modeled','missing']}},additionalProperties:false},annotations:{readOnlyHint:true},execute:(input:any)=>{if(input.system&&!data.systems[input.system])throw new Error('Unknown system');if(input.status&&!['all','modeled','missing'].includes(input.status))throw new Error('Invalid status');return data.parts.filter(p=>(!input.system||p.system===input.system)&&(!input.status||input.status==='all'||p.status===input.status)).map(p=>({id:p.id,name:p.name,status:p.status,accuracy:p.accuracy,geometryCoverage:evidence?.records.find(r=>r.id===p.id)?.geometry??'unresolved',evidence:evidence?.records.find(r=>r.id===p.id)?.reviews??[]}))}},{name:'select_assembly_part',description:'Select a component in the visible assembly and show its validation status. Missing geometry has no 3D highlight.',inputSchema:{type:'object',properties:{partId:{type:'string'}},required:['partId'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:any)=>{const p=data.parts.find(p=>p.id===input.partId);if(!p)throw new Error('Unknown part ID');choose(p.id);await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));return{id:p.id,status:p.status,accuracy:p.accuracy}}}];for(const t of tools){try{Promise.resolve(ctx.registerTool(t,{signal:life.signal})).catch(()=>{})}catch{}}return()=>life.abort()},[data,evidence]);
 return <div className="assembly-app"><header className="assembly-header"><a className="brand" href={appPath("/")}><span className="brand-mark"><Wrench size={21}/></span>wrenchwise<span className="alpha">ALPHA</span></a><a className="back-workshop" href={appPath("/research")}>References</a><a className="back-workshop" href={appPath("/")}><ChevronLeft size={15}/>Guides & parts</a></header><main className="assembly-main"><div className="assembly-heading"><div><h1>{learning?'Engine-bay layout':study?.title||'Component reference'}</h1><p>2000 Lexus GS300 · US · LHD · 2JZ-GE VVT-i</p></div><div className="model-progress" hidden><span><strong>{modeled}</strong>modeled groups</span><span><strong>{counts?.absentGeometry??missing}</strong>{counts?'geometry absent':'legacy gap records'}</span><span><strong>{counts?.unresolvedRecords??'—'}</strong>coverage unresolved</span><span><strong>{counts?.verifiedParts??'—'}</strong>verified parts</span></div></div><div className="accuracy-banner"><ShieldAlert size={19}/><span><strong>Approximate geometry.</strong> Use factory references for dimensions and service specifications.</span><a href="#assembly-details" onClick={()=>{setBottomTab("validation");setLearning(false)}}>See evidence & gaps</a></div>{error&&<p role="alert" className="error-message">{error}</p>}
 <div className="lesson-mode" role="group" aria-label="Learning mode"><button aria-pressed={learning} onClick={()=>setLearning(true)}>Guided learning</button><button aria-pressed={!learning} onClick={()=>setLearning(false)}>Explore systems</button></div>
 {!learning&&<details className="reference-view-switcher"><summary>Change component view</summary><section className="service-studies" aria-label="Reference-based mechanical exploration"><div className="service-heading"><div><span className="eyebrow orange">GS300 MECHANICAL STUDIES</span><h2>Explore a service area</h2></div><p>Reference-informed anatomy · Geometry unverified</p></div><div className="service-presets">{serviceStudies.map(s=><button key={s.id} aria-pressed={studyId===s.id} onClick={()=>selectStudy(s.id)}><small>{s.topic}</small>{s.title}</button>)}</div></section></details>}
 <div className={"assembly-layout "+(learning?"learning-layout":"")}>{learning&&data&&<GuidedLesson onStudy={selectStudy} onPart={choose} activeStudy={studyId} parts={data.parts} sources={data.sources}/>}<aside className="system-sidebar" hidden={learning}><h2><Layers size={16}/>Assembly layers</h2><div className="layer-actions"><button onClick={()=>showView('vehicle')}>Show all</button><button onClick={()=>setVisible([])}>Hide all</button></div>{data&&Object.entries(data.systems).map(([id,label])=><div className="system-row" key={id}><Checkbox id={'system-'+id} checked={visible.includes(id)} onCheckedChange={v=>{setStudyId(null);setVisible(current=>v?[...current,id]:current.filter(k=>k!==id))}}/><label htmlFor={'system-'+id}>{label}</label><button title={'Isolate '+label} aria-label={'Isolate '+label} onClick={()=>{setStudyId(null);setVisible([id]);setView(id==='engine'||id==='transmission'?id:'vehicle');setReset(r=>r+1)}}><Eye size={14}/></button></div>)}<div className="explode-control"><label htmlFor="explosion">Exploded assembly <span>{Math.round(explode*100)}%</span></label><Slider id="explosion" aria-label="Exploded assembly" value={[explode]} max={1} step={.05} onValueChange={v=>setExplode(v[0])}/></div><div className="cutaway-control"><Checkbox id="cutaway" checked={cutaway} onCheckedChange={v=>setCutaway(v===true)}/><label htmlFor="cutaway">Remove casing shells</label></div><p className="sidebar-note">Hides engine, transmission, and differential shells to reveal the provisional internals.</p></aside>
 <section className="assembly-stage"><div className="assembly-stage-top"><span className="pill">INTERACTIVE ANATOMY</span><span>{study?.topic||'Explore a system'}</span></div>{data&&<AssemblyViewer showGrid={!study} visible={visible} selected={selected} explode={explode} cutaway={cutaway} cameraView={view} reset={reset} onSelect={choose} hiddenParts={study?.hidden} onlyParts={study?.only} partOffsets={study?.offsets} focusIds={study?.focus}/>}<div className="assembly-view-tabs">{[['vehicle','Full vehicle'],['engine','Engine bay'],['transmission','Transmission'],['underbody','Underbody']].map(([id,label])=><button key={id} aria-pressed={view===id} className={view===id?'active':''} onClick={()=>showView(id)}>{label}</button>)}</div><button className="assembly-reset" title="Reset camera" aria-label="Reset camera" onClick={()=>setReset(r=>r+1)}><RotateCcw size={17}/></button><div className="assembly-hint">Drag to orbit · Scroll to zoom · Click a part</div></section>
 <aside className="part-inspector"><div className="eyebrow">PART INSPECTOR</div>{part?<><span className={'part-status '+part.status}>{reviewed?({present:'Geometry modeled',absent:'Geometry absent',partial:'Partial coverage',unresolved:'Coverage unresolved'}[reviewed.geometry]):part.status==='modeled'?'Geometry modeled':'Legacy gap record'}</span><h2>{part.name}</h2><code>{part.id}</code><dl><dt>System</dt><dd>{data?.systems[part.system]}</dd><dt>Evidence status</dt><dd>{evidenceError||(!evidence?'Loading evidence…':'No complete part verification')}</dd>{reviewed?.reviews.map(r=><span key={r.domain} className="evidence-review-row"><dt>{r.domain}</dt><dd>{r.status}</dd></span>)}<dt>OEM part number</dt><dd>Not established</dd><dt>Geometry source</dt><dd>{part.source}</dd>{reviewed?.claimIds.map(id=>{const c=evidence?.claims.find(c=>c.id===id);return c?<span className="evidence-review-row" key={id}><dt>{c.subject}</dt><dd>{c.value} {c.unit}<small className="quantity-scope">{c.section} · Documented, not physically checked</small></dd></span>:null})}{part.dimensionsMetres&&<><dt>Mesh bounds · not OEM measurements</dt><dd>{part.dimensionsMetres.map(x=>Math.round(x*1000)).join(' × ')} mm</dd></>}</dl><p>{reviewed?.notes||part.notes}</p>{reviewed&&reviewed.relatedPartIds.length>0&&<div><strong>Related geometry · reconciliation pending</strong>{reviewed.relatedPartIds.map(id=><button className="text-button" key={id} onClick={()=>choose(id)}>{data?.parts.find(p=>p.id===id)?.name||id}</button>)}</div>}{part.sourceRefs?.map(id=>{const ref=data?.sources.find(s=>s.id===id);return ref?<a className="evidence-link" key={id} href={ref.url} target="_blank" rel="noreferrer">{ref.title}<ExternalLink size={13}/></a>:null})}{part.status==='modeled'&&<button className="secondary-btn" onClick={()=>{setStudyId(null);setVisible([part.system]);setView(part.system==='engine'||part.system==='transmission'?part.system:'vehicle');setReset(r=>r+1)}}>Isolate this system</button>}</>:<div className="inspect-empty"><Box size={32}/><h2>Start with a component.</h2><p>Click the model or select an item in the inventory below to inspect its source and validation status.</p></div>}<div className="scale-note"><strong>Model space: metres</strong><span>Scaled from published overall dimensions. Individual part dimensions are estimates.</span></div></aside></div>
 {study&&<div className="service-detail"><div>{learning&&<h3>{study.title}</h3>}<p>{study.summary}</p><p className="service-limit">{study.limit}</p><div className="service-part-links">{study.parts.map(id=><button key={id} aria-pressed={selected===id} onClick={()=>setSelected(id)}>{data?.parts.find(p=>p.id===id)?.name||id}</button>)}</div></div><div><span className="eyebrow">REFERENCE</span><p>{study.reference}</p>{study.sourceIds.map(id=>{const ref=data?.sources.find(s=>s.id===id);return ref?<a key={id} href={ref.url} target="_blank" rel="noreferrer">{ref.title}<ExternalLink size={13}/></a>:null})}<button className="text-button" onClick={()=>showView('vehicle')}>Return to full vehicle</button></div></div>}
 <details className="assembly-reference-details" open={!learning}><summary>Component inventory, sources & validation</summary><Tabs value={bottomTab} onValueChange={setBottomTab} id="assembly-details" className="assembly-bottom"><TabsList variant="line" className="assembly-bottom-tabs"><TabsTrigger value="inventory">Component inventory</TabsTrigger><TabsTrigger value="sources">Model sources</TabsTrigger><TabsTrigger value="validation">Evidence & next build</TabsTrigger></TabsList><TabsContent value="inventory"><div className="inventory-toolbar"><div className="inventory-search"><Search size={17}/><Input aria-label="Search component inventory" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search every listed part, system, or ID…"/></div><Select value={systemFilter} onValueChange={setSystemFilter}><SelectTrigger aria-label="Filter by system"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All systems</SelectItem>{data&&Object.entries(data.systems).map(([id,label])=><SelectItem key={id} value={id}>{label}</SelectItem>)}</SelectContent></Select><Select value={filter} onValueChange={setFilter}><SelectTrigger aria-label="Filter by geometry status"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All statuses</SelectItem><SelectItem value="modeled">Modeled</SelectItem><SelectItem value="missing">Geometry absent</SelectItem><SelectItem value="unresolved">Coverage unresolved</SelectItem></SelectContent></Select><span>{shown.length} items</span></div><p className="inventory-disclaimer">A working assembly inventory, not an exhaustive OEM bill of materials. Six legacy gaps now track partial or unresolved coverage separately; they have not been declared complete. Counts include grouped fasteners and subassemblies. Selected fastener quantities now have cited documentation. Coordinates, dimensions, part numbers, fitment and omitted items still require verification.</p><div className="inventory-list">{shown.map(p=><button className={'inventory-row '+(selected===p.id?'selected':'')} key={p.id} onClick={()=>choose(p.id)}><Box size={15}/><span><strong>{p.name}</strong><small>{p.id}</small></span><span className="inventory-system">{data?.systems[p.system]}</span><span className={'part-status '+p.status}>{p.status==='modeled'?'Modeled · unverified':evidence?.records.find(r=>r.id===p.id)?.geometry==='absent'?'Geometry absent':'Coverage unresolved'}</span></button>)}{!shown.length&&<p>No matching components.</p>}</div></TabsContent>
 <TabsContent value="sources"><p><a className="evidence-link" href={appPath("/research")}>Open the source audit for all 11 catalog vehicles →</a></p><div className="research-grid"><article><span className="source-chip">FREE · CC BY 4.0</span><h3>Lexus GS300 exterior</h3><p>Jean Wally’s™ · 52.5k triangles. The thumbnail shows an S160-style exterior. Exact model year, underbody, engine, and transmission coverage are unconfirmed. Download requires a Sketchfab login.</p><a href="https://sketchfab.com/3d-models/lexus-gs300-7a7e13c0aeb641b68d6ee72ee4ab8cf6" target="_blank" rel="noreferrer">View candidate <ExternalLink size={14}/></a></article><article><span className="source-chip">FREE · CC BY</span><h3>Lexus GS300 candidate</h3><p>Romanov_13 · 403.8k triangles. A second exterior candidate. Exact generation, mechanical contents, dimensions, and provenance require inspection before use.</p><a href="https://sketchfab.com/3d-models/lexus-gs300-02c2d4441b374c749269fa030d2c9ede" target="_blank" rel="noreferrer">View candidate <ExternalLink size={14}/></a></article><article><span className="source-chip reject">NOT A MATCH</span><h3>2JZ-GE engine</h3><p>rpautomotive · 286.6k triangles. Listed as non-VVT-i, unlike this car. CC BY-NC-SA also restricts commercial reuse. Not incorporated into the assembly.</p><a href="https://sketchfab.com/3d-models/2jz-ge-engine-0289ac9eb3fb4e7eba1535fba6043024" target="_blank" rel="noreferrer">Read listing <ExternalLink size={14}/></a></article></div><p className="inventory-disclaimer">The current exterior uses David_Holiday’s GS300 mesh under CC BY 4.0, with material and trim adaptations. The earlier candidates above remain alternatives. “Free to download” does not establish exact fitment, completeness, or permission for unrestricted redistribution.</p></TabsContent>
 <TabsContent value="validation"><div className="validation-layout"><section><h3>What the scale is based on</h3><div className="dimension-grid">{data&&Object.entries({Length:data.dimensionTargets.lengthMetres,'Body width':data.dimensionTargets.bodyWidthMetres,Height:data.dimensionTargets.heightMetres,Wheelbase:data.dimensionTargets.wheelbaseMetres}).map(([k,v])=><div key={k}><span>{k}</span><strong>{(v*1000).toFixed(1)} <small>mm</small></strong></div>)}</div><p>These are targets converted from rounded brochure dimensions. They do not validate the body shape, suspension hardpoints, or engine and transmission geometry.</p>{data?.sources.map(s=><a className="evidence-link" key={s.id} href={s.url} target="_blank" rel="noreferrer">{s.title}<ExternalLink size={14}/></a>)}</section><section><h3>Next validation: measured service geometry</h3><ol><li>Measure or scan the reference-informed VVT-i engine and A650E assembly.</li><li>Validate the rebuilt pump, pulleys, tensioner, brackets, fasteners and valve-body layers individually.</li><li>Validate mating surfaces, clearances, belt routing, and timing marks.</li><li>Author and review the first repair procedure against licensed service information.</li></ol>{data?.openIssues.map(issue=><p className="open-issue" key={issue}>{issue}</p>)}</section></div></TabsContent></Tabs></details>
 <details className="assembly-source-tools" id="validation"><summary>Model provenance & contributor resources</summary><p>Original mechanical geometry is MIT-licensed. The adapted GS300 exterior by David_Holiday is CC BY 4.0. These contributor files support model development; they are not repair instructions.</p><a href={appPath('/models/gs300-assembly.glb')} download>Assembly source file</a><a href={appPath('/models/parts-inventory.txt')}>Parts inventory</a><a href={appPath('/models/blender-modeling-source.zip')} download>Blender source archive</a><a href={appPath('/research')}>Source audit & attribution</a></details><footer><span>Wrenchwise · Provisional geometry · MIT + CC BY 4.0</span><span>Not affiliated with Lexus or Toyota</span></footer></main></div>
}
